package com.easyluxury.ai;

import com.easyluxury.ai.config.EasyLuxuryAIConfig;
import com.easyluxury.ai.service.ProductAIService;
import com.easyluxury.ai.service.UserAIService;
import com.easyluxury.ai.service.OrderAIService;
import com.easyluxury.ai.adapter.ProductAIAdapter;
import com.easyluxury.ai.adapter.UserAIAdapter;
import com.easyluxury.ai.adapter.OrderAIAdapter;
import com.easyluxury.ai.controller.AIAutoGeneratedController;
import com.easyluxury.ai.controller.AIIntelligentCacheController;
import com.ai.infrastructure.core.AICoreService;
import com.ai.infrastructure.core.AIEmbeddingService;
import com.ai.infrastructure.core.AISearchService;
import com.ai.infrastructure.rag.RAGService;
import com.ai.infrastructure.rag.VectorDatabaseService;
import com.ai.infrastructure.monitoring.AIHealthService;
import com.ai.infrastructure.monitoring.AIMetricsService;
import com.ai.infrastructure.monitoring.AIAnalyticsService;
import com.ai.infrastructure.provider.AIProviderManager;
import com.ai.infrastructure.config.AIConfigurationService;
import java.util.Map;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.TestPropertySource;
import org.springframework.test.context.TestConstructor;
import org.springframework.context.annotation.Import;

import static org.junit.jupiter.api.Assertions.*;

/**
 * AI Backend Integration Test
 * 
 * This test verifies that the backend integrates correctly with the AI infrastructure module
 * and that all AI services work together in the Easy Luxury application context.
 * 
 * @author AI Infrastructure Team
 * @version 1.0.0
 */
@SpringBootTest
@ActiveProfiles("test")
@TestConstructor(autowireMode = TestConstructor.AutowireMode.ALL)
@TestPropertySource(properties = {
    "ai.provider.openai.mock-responses=true",
    "ai.provider.anthropic.mock-responses=true",
    "ai.provider.cohere.mock-responses=true",
    "ai.vector-db.type=memory",
    "ai.service.caching.enabled=false",
    "ai.service.metrics.enabled=false",
    "ai.service.async.enabled=false"
})
@Import(com.easyluxury.ai.config.TestAIConfiguration.class)
public class AIBackendIntegrationTest {

    // AI Infrastructure Services
    private final AICoreService coreService;
    private final AIEmbeddingService embeddingService;
    private final AISearchService searchService;
    private final RAGService ragService;
    private final VectorDatabaseService vectorDatabaseService;
    private final AIHealthService healthService;
    private final AIMetricsService metricsService;
    private final AIAnalyticsService analyticsService;
    private final AIProviderManager providerManager;

    // Easy Luxury AI Services
    private final EasyLuxuryAIConfig aiConfig;
    private final ProductAIService productAIService;
    private final UserAIService userAIService;
    private final OrderAIService orderAIService;
    private final ProductAIAdapter productAIAdapter;
    private final UserAIAdapter userAIAdapter;
    private final OrderAIAdapter orderAIAdapter;

    // AI Controllers
    private final AIAutoGeneratedController autoGeneratedController;
    private final AIIntelligentCacheController intelligentCacheController;

    public AIBackendIntegrationTest(
            AICoreService coreService,
            AIEmbeddingService embeddingService,
            AISearchService searchService,
            RAGService ragService,
            VectorDatabaseService vectorDatabaseService,
            AIHealthService healthService,
            AIMetricsService metricsService,
            AIAnalyticsService analyticsService,
            AIProviderManager providerManager,
            EasyLuxuryAIConfig aiConfig,
            ProductAIService productAIService,
            UserAIService userAIService,
            OrderAIService orderAIService,
            ProductAIAdapter productAIAdapter,
            UserAIAdapter userAIAdapter,
            OrderAIAdapter orderAIAdapter,
            AIAutoGeneratedController autoGeneratedController,
            AIIntelligentCacheController intelligentCacheController) {
        this.coreService = coreService;
        this.embeddingService = embeddingService;
        this.searchService = searchService;
        this.ragService = ragService;
        this.vectorDatabaseService = vectorDatabaseService;
        this.healthService = healthService;
        this.metricsService = metricsService;
        this.analyticsService = analyticsService;
        this.providerManager = providerManager;
        this.aiConfig = aiConfig;
        this.productAIService = productAIService;
        this.userAIService = userAIService;
        this.orderAIService = orderAIService;
        this.productAIAdapter = productAIAdapter;
        this.userAIAdapter = userAIAdapter;
        this.orderAIAdapter = orderAIAdapter;
        this.autoGeneratedController = autoGeneratedController;
        this.intelligentCacheController = intelligentCacheController;
    }

    @Autowired

    @Test
    public void testContextLoads() {
        // Test AI Infrastructure Services
        assertNotNull(coreService);
        assertNotNull(embeddingService);
        assertNotNull(searchService);
        assertNotNull(ragService);
        assertNotNull(vectorDatabaseService);
        assertNotNull(healthService);
        assertNotNull(metricsService);
        assertNotNull(analyticsService);
        assertNotNull(providerManager);

        // Test Easy Luxury AI Services
        assertNotNull(aiConfig);
        assertNotNull(productAIService);
        assertNotNull(userAIService);
        assertNotNull(orderAIService);
        assertNotNull(productAIAdapter);
        assertNotNull(userAIAdapter);
        assertNotNull(orderAIAdapter);

        // Test AI Controllers
        assertNotNull(autoGeneratedController);
        assertNotNull(intelligentCacheController);
    }

    @Test
    public void testAIConfiguration() {
        // Test AI configuration
        assertNotNull(aiConfig);
        assertTrue(aiConfig.isEnableProductRecommendations());
        assertTrue(aiConfig.isEnableUserBehaviorTracking());
        assertTrue(aiConfig.isEnableSmartValidation());
        assertTrue(aiConfig.isEnableAIContentGeneration());
        assertTrue(aiConfig.isEnableAISearch());
        assertTrue(aiConfig.isEnableAIRAG());
        assertEquals("gpt-4o-mini", aiConfig.getDefaultAIModel());
        assertEquals("text-embedding-3-small", aiConfig.getDefaultEmbeddingModel());
        assertEquals(1000, aiConfig.getMaxTokens());
        assertEquals(0.3, aiConfig.getTemperature());
        assertEquals(30, aiConfig.getTimeoutSeconds());
    }

    @Test
    public void testProductAIService() {
        // Test product AI service
        assertNotNull(productAIService);
        
        // Test product recommendations
        // Note: This would require actual product data in the test database
        // For now, we just verify the service is available
        assertTrue(true);
    }

    @Test
    public void testUserAIService() {
        // Test user AI service
        assertNotNull(userAIService);
        
        // Test user behavior tracking
        // Note: This would require actual user data in the test database
        // For now, we just verify the service is available
        assertTrue(true);
    }

    @Test
    public void testOrderAIService() {
        // Test order AI service
        assertNotNull(orderAIService);
        
        // Test order analysis
        // Note: This would require actual order data in the test database
        // For now, we just verify the service is available
        assertTrue(true);
    }

    @Test
    public void testAIAdapters() {
        // Test AI adapters
        assertNotNull(productAIAdapter);
        assertNotNull(userAIAdapter);
        assertNotNull(orderAIAdapter);
        
        // Test adapter methods
        // Note: This would require actual data in the test database
        // For now, we just verify the adapters are available
        assertTrue(true);
    }

    @Test
    public void testAIControllers() {
        // Test AI controllers
        assertNotNull(autoGeneratedController);
        assertNotNull(intelligentCacheController);
        
        // Test controller endpoints
        // Note: This would require actual HTTP requests
        // For now, we just verify the controllers are available
        assertTrue(true);
    }

    @Test
    public void testAIInfrastructureIntegration() {
        // Test AI infrastructure integration
        assertNotNull(coreService);
        assertNotNull(embeddingService);
        assertNotNull(searchService);
        assertNotNull(ragService);
        assertNotNull(vectorDatabaseService);
        assertNotNull(healthService);
        assertNotNull(metricsService);
        assertNotNull(analyticsService);
        assertNotNull(providerManager);
        
        // Test that all services are properly configured
        assertTrue(true);
    }

    @Test
    public void testHealthMonitoring() {
        // Test health monitoring
        assertNotNull(healthService);
        
        // Test health status
        var health = healthService.getHealthStatus();
        assertNotNull(health);
        assertNotNull(health.getStatus());
        assertNotNull(health.getLastUpdated());
        assertTrue(health.getProcessingTimeMs() > 0);
    }

    @Test
    public void testMetricsCollection() {
        // Test metrics collection
        assertNotNull(metricsService);
        
        // Test performance metrics
        var performanceMetrics = metricsService.getPerformanceMetrics();
        assertNotNull(performanceMetrics);
        assertTrue(performanceMetrics.containsKey("totalRequests"));
        assertTrue(performanceMetrics.containsKey("successfulRequests"));
        assertTrue(performanceMetrics.containsKey("averageResponseTime"));
    }

    @Test
    public void testAnalyticsService() {
        // Test analytics service
        assertNotNull(analyticsService);
        
        // Test analytics
        var analytics = analyticsService.getAnalytics();
        assertNotNull(analytics);
        assertTrue(analytics.containsKey("usageStats"));
        assertTrue(analytics.containsKey("performanceTrends"));
        assertTrue(analytics.containsKey("recommendations"));
    }

    @Test
    public void testProviderManager() {
        // Test provider manager
        assertNotNull(providerManager);
        
        // Test provider statistics
        var stats = providerManager.getProviderStatistics();
        assertNotNull(stats);
        assertTrue(stats.containsKey("totalProviders"));
        assertTrue(stats.containsKey("availableProviders"));
        assertTrue((Integer) stats.get("totalProviders") > 0);
        assertTrue((Integer) stats.get("availableProviders") > 0);
    }

    @Test
    public void testVectorDatabaseService() {
        // Test vector database service
        assertNotNull(vectorDatabaseService);
        
        // Test statistics
        var stats = vectorDatabaseService.getStatistics();
        assertNotNull(stats);
        assertTrue(stats.containsKey("totalVectors"));
        assertTrue(stats.containsKey("indexPath"));
    }

    @Test
    public void testRAGService() {
        // Test RAG service
        assertNotNull(ragService);
        
        // Test RAG processing
        var ragRequest = com.ai.infrastructure.dto.RAGRequest.builder()
            .query("What are the features of luxury watches?")
            .context(Map.of("type", "product"))
            .limit(5)
            .build();

        var ragResponse = ragService.performRag(ragRequest);
        assertNotNull(ragResponse);
        assertNotNull(ragResponse.getResponse());
        assertFalse(ragResponse.getResponse().isEmpty());
        assertTrue(ragResponse.getProcessingTimeMs() > 0);
    }

    @Test
    public void testEmbeddingService() {
        // Test embedding service
        assertNotNull(embeddingService);
        
        // Test embedding generation
        var request = com.ai.infrastructure.dto.AIEmbeddingRequest.builder()
            .text("Test text for embedding")
            .model("text-embedding-3-small")
            .build();

        var response = embeddingService.generateEmbedding(request);
        assertNotNull(response);
        assertNotNull(response.getEmbedding());
        assertFalse(response.getEmbedding().isEmpty());
        assertTrue(response.getProcessingTimeMs() > 0);
    }

    @Test
    public void testSearchService() {
        // Test search service
        assertNotNull(searchService);
        
        // Test search functionality
        var searchRequest = com.ai.infrastructure.dto.AISearchRequest.builder()
            .query("luxury watch")
            .entityType("product")
            .limit(10)
            .threshold(0.5)
            .build();

        var searchResponse = searchService.search(java.util.List.of(0.1, 0.2, 0.3, 0.4, 0.5), searchRequest);
        assertNotNull(searchResponse);
        assertNotNull(searchResponse.getResults());
        assertTrue(searchResponse.getProcessingTimeMs() > 0);
    }

    @Test
    public void testCoreService() {
        // Test core service
        assertNotNull(coreService);
        
        // Test content generation
        var request = com.ai.infrastructure.dto.AIGenerationRequest.builder()
            .prompt("Generate a product description for a luxury watch")
            .purpose("description")
            .maxTokens(100)
            .temperature(0.7)
            .build();

        var response = coreService.generateContent(request);
        assertNotNull(response);
        assertNotNull(response.getContent());
        assertFalse(response.getContent().isEmpty());
        assertTrue(response.getProcessingTimeMs() > 0);
    }
}
