'use client';

import NextLink from 'next/link';
import {
  AutoAwesomeOutlined,
  OpenInNewOutlined,
  SendOutlined,
} from '@mui/icons-material';
import { Box, Button, Stack, Typography } from '@mui/material';
import StudioAssistantCard, { type StudioAssistantContext } from './StudioAssistantCard';
import {
  DotLabel,
  PastelChip,
  SectionTitle,
  StatusChip,
  Surface,
  appleColors,
  formatLabel,
} from './PlatformComponents';
import type {
  Milestone,
  ProjectWorkspace,
  QuoteProposal,
  SupportRequest,
} from './types';

interface AssistantActionHandlers {
  onConfirmAction?: (action: Record<string, unknown>) => Promise<void> | void;
  actionDisabledReason?: (action: Record<string, unknown>) => string;
}

const supportPriorityAccent = (status?: string) => {
  if (!status) return appleColors.purple;
  if (status.includes('BLOCK') || status.includes('REJECT') || status.includes('URGENT')) {
    return appleColors.red;
  }
  if (
    status.includes('REVIEW')
    || status.includes('NEGOTIATION')
    || status.includes('AWAITING')
    || status.includes('SUBMITTED')
  ) {
    return appleColors.amber;
  }
  if (
    status.includes('ACTIVE')
    || status.includes('ACCEPT')
    || status.includes('DELIVER')
    || status.includes('SIGNED')
    || status.includes('ON_TRACK')
  ) {
    return appleColors.green;
  }
  return appleColors.purple;
};

export function OwnerAiBriefPanel({
  fallbackReason,
  isDisabled,
  isFetching,
  mode,
  recommendationRationale,
  suggestions,
  onSuggest,
}: {
  fallbackReason?: string | undefined;
  isDisabled: boolean;
  isFetching: boolean;
  mode?: string | undefined;
  recommendationRationale?: string | undefined;
  suggestions: string[];
  onSuggest: () => void;
}) {
  const live = Boolean(mode && mode !== 'FALLBACK');
  const visibleSuggestions = (suggestions.length
    ? suggestions
    : [
        'Explain productization readiness',
        'Recommend lifecycle services from evidence',
        'Prepare the next package action',
      ]
  ).slice(0, 3);

  return (
    <Surface>
      <SectionTitle
        title="AI Owner Brief"
        action={
          <Stack direction="row" spacing={1} alignItems="center">
            <PastelChip
              label={mode ? (live ? 'LoomAI live' : 'ProdUS fallback') : 'On demand'}
              accent={live ? appleColors.purple : appleColors.blue}
            />
            <Button
              size="small"
              variant="outlined"
              startIcon={<AutoAwesomeOutlined />}
              disabled={isDisabled || isFetching}
              onClick={onSuggest}
              sx={{ minHeight: 34 }}
            >
              {isFetching ? 'Thinking...' : 'Suggest'}
            </Button>
          </Stack>
        }
      />
      <Stack direction="row" spacing={1.5} alignItems="center">
        <Box
          sx={{
            width: 52,
            height: 52,
            borderRadius: 1,
            bgcolor: '#f1efff',
            color: appleColors.purple,
            display: 'grid',
            placeItems: 'center',
            flexShrink: 0,
          }}
        >
          <AutoAwesomeOutlined />
        </Box>
        <Box>
          <Typography variant="h4">Productization clarity</Typography>
          <Typography color="success.main" sx={{ fontWeight: 800 }}>
            Evidence-led next steps
          </Typography>
        </Box>
      </Stack>
      <Typography color="text.secondary" sx={{ mt: 2, lineHeight: 1.7 }}>
        {recommendationRationale
          || 'Use lifecycle services, plan evidence, and verified teams to keep productization decisions concrete.'}
      </Typography>
      <Stack spacing={1} sx={{ mt: 2 }}>
        {visibleSuggestions.map((suggestion) => (
          <Box
            key={suggestion}
            sx={{
              p: 1.25,
              border: '1px solid',
              borderColor: appleColors.line,
              borderRadius: 1,
              background: 'rgba(248, 250, 252, 0.78)',
            }}
          >
            <Stack direction="row" spacing={1} alignItems="center">
              <AutoAwesomeOutlined sx={{ color: appleColors.purple, fontSize: 18 }} />
              <Typography variant="body2" sx={{ fontWeight: 800 }}>
                {suggestion}
              </Typography>
            </Stack>
          </Box>
        ))}
      </Stack>
      {fallbackReason && (
        <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mt: 1.5 }}>
          {formatLabel(fallbackReason)}. Suggestions are generated by the ProdUS deterministic
          fallback until LoomAI is configured.
        </Typography>
      )}
    </Surface>
  );
}

export function OwnerDeliveryWorkspacePanel({
  assistantActions,
  assistantContext,
  blockedMilestoneCount,
  milestones,
  selectedMilestone,
  workspace,
}: {
  assistantActions: AssistantActionHandlers;
  assistantContext: StudioAssistantContext;
  blockedMilestoneCount: number;
  milestones: Milestone[];
  selectedMilestone?: Milestone | undefined;
  workspace?: ProjectWorkspace | undefined;
}) {
  return (
    <Surface>
      <SectionTitle title="Delivery Workspace" action={workspace && <StatusChip label={workspace.status} />} />
      {workspace ? (
        <Stack spacing={1.5}>
          <Typography sx={{ fontWeight: 900 }}>{workspace.name}</Typography>
          {milestones.slice(0, 5).map((milestone) => (
            <Stack
              key={milestone.id}
              direction="row"
              spacing={1}
              justifyContent="space-between"
              sx={{ borderTop: '1px solid', borderColor: 'divider', pt: 1 }}
            >
              <Box>
                <Typography variant="body2" sx={{ fontWeight: 800 }}>
                  {milestone.title}
                </Typography>
                <Typography variant="caption" color="text.secondary">
                  {milestone.dueDate || 'No date'}
                </Typography>
              </Box>
              <StatusChip label={milestone.status} />
            </Stack>
          ))}
          <StudioAssistantCard
            title="AI Milestone Evidence"
            description="Check what the current milestone needs before owner approval or team handoff."
            prompt={`Do not call tools for this answer. Review milestone and evidence readiness for ${selectedMilestone?.title || workspace.name}. Visible workspace "${workspace.name}" is ${workspace.status}. Current milestone details: title "${selectedMilestone?.title || 'workspace summary'}", status "${selectedMilestone?.status || workspace.status}", due date "${selectedMilestone?.dueDate || 'not recorded'}", description "${selectedMilestone?.description || 'not recorded'}". Explain missing acceptance evidence, scanner proof, owner review risks, and the next safe decision. Do not approve the milestone automatically.`}
            conversationId={`studio-milestone-${workspace.id}-${selectedMilestone?.id || 'summary'}`}
            context={assistantContext}
            {...assistantActions}
            accent={blockedMilestoneCount ? appleColors.red : appleColors.green}
            compact
            cta="Check Evidence"
          />
          <Button
            component={NextLink}
            href="/workspaces"
            variant="outlined"
            endIcon={<OpenInNewOutlined />}
            sx={{ minHeight: 42 }}
          >
            Manage workspace
          </Button>
        </Stack>
      ) : (
        <Typography variant="body2" color="text.secondary">
          A workspace appears after service plan handoff.
        </Typography>
      )}
    </Surface>
  );
}

export function OwnerSupportRiskPanel({
  supportRequests,
}: {
  supportRequests: SupportRequest[];
}) {
  return (
    <Surface
      sx={{
        background: supportRequests.some((request) => request.slaStatus === 'OVERDUE')
          ? '#fff7f8'
          : '#f6fffb',
      }}
    >
      <SectionTitle title="Support and Risk" />
      {supportRequests.length ? (
        <Stack spacing={1.25}>
          {supportRequests.slice(0, 4).map((request) => (
            <Stack
              key={request.id}
              direction="row"
              spacing={1}
              justifyContent="space-between"
              alignItems="flex-start"
            >
              <Box>
                <Typography variant="body2" sx={{ fontWeight: 800 }}>
                  {request.title}
                </Typography>
                <Typography variant="caption" color="text.secondary">
                  {formatLabel(request.status)} · {formatLabel(request.slaStatus)}
                </Typography>
              </Box>
              <PastelChip
                label={formatLabel(request.priority)}
                accent={supportPriorityAccent(request.priority)}
              />
            </Stack>
          ))}
        </Stack>
      ) : (
        <Typography variant="body2" color="text.secondary">
          No support requests are attached to this product.
        </Typography>
      )}
    </Surface>
  );
}

export function OwnerNextDecisionPanel({
  blockedMilestoneCount,
  buildTargetRequirementId,
  hasServicePlan,
  hasWorkspace,
  isBuilding,
  proposals,
  onBuildPlan,
}: {
  blockedMilestoneCount: number;
  buildTargetRequirementId?: string | undefined;
  hasServicePlan: boolean;
  hasWorkspace: boolean;
  isBuilding: boolean;
  proposals: QuoteProposal[];
  onBuildPlan: (requirementId: string) => void;
}) {
  const ownerAcceptedProposal = proposals.some((proposal) => proposal.status === 'OWNER_ACCEPTED');

  return (
    <Surface>
      <SectionTitle title="Next Decision" />
      <Stack spacing={1.25}>
        {!hasServicePlan && <DotLabel label="Create the service plan" color={appleColors.amber} />}
        {hasServicePlan && !ownerAcceptedProposal && (
          <DotLabel label="Compare and accept a team proposal" color={appleColors.purple} />
        )}
        {hasServicePlan && hasWorkspace && (
          <DotLabel
            label="Review milestone evidence"
            color={blockedMilestoneCount ? appleColors.red : appleColors.green}
          />
        )}
        {buildTargetRequirementId && !hasServicePlan && (
          <Button
            variant="contained"
            startIcon={<SendOutlined />}
            onClick={() => onBuildPlan(buildTargetRequirementId)}
            disabled={isBuilding}
          >
            Create service plan
          </Button>
        )}
      </Stack>
    </Surface>
  );
}
