'use client';

import { AutoAwesomeOutlined } from '@mui/icons-material';
import { Box, Button, Stack, Typography } from '@mui/material';
import {
  PastelChip,
  SectionTitle,
  Surface,
  appleColors,
  formatLabel,
} from './PlatformComponents';

export default function OwnerAiBriefPanel({
  fallbackReason,
  isDisabled,
  isFetching,
  mode,
  recommendationRationale,
  suggestions,
  onSuggest,
}: {
  fallbackReason?: string | undefined;
  isDisabled: boolean;
  isFetching: boolean;
  mode?: string | undefined;
  recommendationRationale?: string | undefined;
  suggestions: string[];
  onSuggest: () => void;
}) {
  const live = Boolean(mode && mode !== 'FALLBACK');
  const visibleSuggestions = (suggestions.length
    ? suggestions
    : [
        'Explain product readiness',
        'Recommend lifecycle services from evidence',
        'Prepare the next package action',
      ]
  ).slice(0, 3);

  return (
    <Surface>
      <SectionTitle
        title="AI Owner Brief"
        action={
          <Stack direction="row" spacing={1} alignItems="center">
            <PastelChip
              label={mode ? (live ? 'LoomAI live' : 'ProdUS fallback') : 'On demand'}
              accent={live ? appleColors.purple : appleColors.blue}
            />
            <Button
              size="small"
              variant="outlined"
              startIcon={<AutoAwesomeOutlined />}
              disabled={isDisabled || isFetching}
              onClick={onSuggest}
              sx={{ minHeight: 34 }}
            >
              {isFetching ? 'Thinking...' : 'Suggest'}
            </Button>
          </Stack>
        }
      />
      <Stack direction="row" spacing={1.5} alignItems="center">
        <Box
          sx={{
            width: 52,
            height: 52,
            borderRadius: 1,
            bgcolor: '#f1efff',
            color: appleColors.purple,
            display: 'grid',
            placeItems: 'center',
            flexShrink: 0,
          }}
        >
          <AutoAwesomeOutlined />
        </Box>
        <Box>
          <Typography variant="h4">Product clarity</Typography>
          <Typography color="success.main" sx={{ fontWeight: 800 }}>
            Evidence-led next steps
          </Typography>
        </Box>
      </Stack>
      <Typography color="text.secondary" sx={{ mt: 2, lineHeight: 1.7 }}>
        {recommendationRationale
          || 'Use lifecycle services, plan evidence, and verified teams to keep product decisions concrete.'}
      </Typography>
      <Stack spacing={1} sx={{ mt: 2 }}>
        {visibleSuggestions.map((suggestion) => (
          <Box
            key={suggestion}
            sx={{
              p: 1.25,
              border: '1px solid',
              borderColor: appleColors.line,
              borderRadius: 1,
              background: 'rgba(248, 250, 252, 0.78)',
            }}
          >
            <Stack direction="row" spacing={1} alignItems="center">
              <AutoAwesomeOutlined sx={{ color: appleColors.purple, fontSize: 18 }} />
              <Typography variant="body2" sx={{ fontWeight: 800 }}>
                {suggestion}
              </Typography>
            </Stack>
          </Box>
        ))}
      </Stack>
      {fallbackReason && (
        <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mt: 1.5 }}>
          {formatLabel(fallbackReason)}. Suggestions are generated by the ProdUS deterministic
          fallback until LoomAI is configured.
        </Typography>
      )}
    </Surface>
  );
}
