package com.produs.catalog;

import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

@Service
@RequiredArgsConstructor
public class CatalogCoreSeedService {

    private final ServiceCategoryRepository categoryRepository;
    private final ServiceModuleRepository moduleRepository;
    private final ServiceDependencyRepository dependencyRepository;
    private final PackageTemplateRepository packageTemplateRepository;
    private final PackageTemplateModuleRepository packageTemplateModuleRepository;
    private final CatalogRuleRepository ruleRepository;
    private final CatalogTemplateDefinitionRepository templateDefinitionRepository;
    private final AICapabilityConfigRepository aiCapabilityConfigRepository;

    @Transactional
    public CatalogSeedResult seedCoreCatalog() {
        Map<String, ServiceCategory> categories = seedCategories();
        Map<String, ServiceModule> modules = seedModules(categories);
        seedDependencies(modules);
        seedPackageTemplates(modules);
        seedTemplateDefinitions();
        seedRules(modules);
        seedAiCapabilityConfigs();
        return new CatalogSeedResult(categories.size(), modules.size());
    }

    private Map<String, ServiceCategory> seedCategories() {
        List<CategorySeed> seeds = List.of(
                new CategorySeed("validation", "Validation", "Product diagnosis, requirements, readiness, and productization scope.", 1),
                new CategorySeed("code-rewrite-refactor", "Code Modernization", "Refactor, rewrite, and clean up product code into maintainable systems.", 2),
                new CategorySeed("security", "Security Hardening", "Auth, API, dependency, privacy, payment, and evidence-backed remediation.", 3),
                new CategorySeed("cloud-devops", "Cloud / DevOps", "Deployment, CI/CD, staging, rollback, monitoring, and production environment control.", 4),
                new CategorySeed("database", "Database / Data", "Schema, migrations, query performance, backups, integrity, and tenant isolation.", 5),
                new CategorySeed("scaling", "Scaling / Performance", "Load, cost, resilience, caching, queues, and architecture readiness for growth.", 6),
                new CategorySeed("launch-gtm-readiness", "Launch Readiness", "Onboarding, analytics, payments, admin tools, beta, docs, and go-live controls.", 7),
                new CategorySeed("operations-support", "Operations / Support", "Maintenance, monitoring, incidents, releases, patching, and ongoing product health.", 8)
        );
        Map<String, ServiceCategory> categories = new LinkedHashMap<>();
        for (CategorySeed seed : seeds) {
            ServiceCategory category = categoryRepository.findBySlug(seed.slug()).orElseGet(ServiceCategory::new);
            category.setSlug(seed.slug());
            category.setName(seed.name());
            category.setDescription(seed.description());
            category.setSortOrder(seed.sortOrder());
            category.setActive(true);
            categories.put(seed.slug(), categoryRepository.save(category));
        }
        return categories;
    }

    private Map<String, ServiceModule> seedModules(Map<String, ServiceCategory> categories) {
        List<ModuleSeed> seeds = List.of(
                module("validation", "validation.product_readiness", "product-readiness-diagnosis", "Product readiness diagnosis", "Assess product, code, infrastructure, data, security, and launch gaps before work is scoped.", "A clear productization decision with evidence-backed blockers, priorities, and next services.", "Product summary, demo, repo access if available, known risks, user flows, target launch moment.", "Diagnosis report; blocker map; recommended service plan; evidence requirements; owner decision log.", "Owner can see what blocks production, what can be deferred, and what service sequence is justified.", "3-5 business days", "$4K-$12K", "Product advisor, technical reviewer, delivery lead", "Diagnosis report, risk register, owner decision record", "diagnosis,scope,recommendation", 1),
                module("validation", "validation.requirements", "requirement-analysis", "Requirements definition", "Convert rough product intent into an implementation-ready productization brief.", "Scope, goals, constraints, and acceptance criteria become concrete enough for teams to price and deliver.", "Business goal, current workflow notes, customer segment, constraints, current blockers.", "Product brief; functional scope; non-functional scope; assumptions; open questions.", "Brief is specific enough to generate services, milestones, acceptance criteria, and proposal scope.", "3-5 business days", "$4K-$12K", "Product advisor, business analyst, technical reviewer", "Product brief, requirements matrix, assumptions log", "requirements,brief,scope", 2),
                module("validation", "validation.architecture", "architecture-readiness-review", "Architecture readiness review", "Review system boundaries, data flows, dependencies, hosting, and operational ownership.", "The owner understands architecture risks before a rewrite, migration, or scale investment begins.", "Architecture notes, repo access, infra diagram, runtime dependencies, integration map.", "Architecture assessment; dependency map; risk sequence; tradeoff notes.", "Architecture findings identify production risks and map each risk to a service or owner decision.", "1-2 weeks", "$8K-$28K", "Architect, backend lead, DevOps reviewer", "Architecture report, dependency diagram, remediation sequence", "architecture,dependency,risk", 3),
                module("validation", "validation.codebase", "codebase-diagnosis", "Codebase diagnosis", "Inspect code health, structure, tests, ownership seams, and maintainability risk.", "The team knows whether to refactor, rewrite, or isolate risky parts before implementation.", "Repository access, build/test command, known fragile workflows, deployment notes.", "Codebase health report; module risk map; build/test status; modernization path.", "Findings include reproduction evidence, maintainability impact, and a recommended modernization plan.", "1-2 weeks", "$8K-$30K", "Senior engineer, QA reviewer", "Repo scan, build log, test report, code risk register", "codebase,refactor,rewrite", 4),
                module("validation", "validation.launch_risk", "launch-readiness-review", "Launch risk review", "Assess release, support, analytics, payment, security, and owner handoff risk before launch.", "The product has a go/no-go decision with launch-critical blockers and mitigations.", "Release target, staging URL, checklist, support plan, payment/onboarding flow notes.", "Launch risk report; go/no-go decision; blocker list; mitigation plan.", "Review covers launch-critical product, engineering, security, support, and business flows.", "1-2 weeks", "$8K-$24K", "Launch lead, technical reviewer, support reviewer", "Launch checklist, go/no-go record, blocker register", "launch,go-live,risk", 5),
                module("validation", "validation.build_vs_rebuild", "build-vs-rebuild-decision", "Build vs rebuild decision", "Determine when to preserve, refactor, rewrite, or replace prototype implementation.", "Owners avoid paying for unnecessary rewrites while still addressing production risk.", "Repo access, product goals, current pain points, timeline, budget, technical constraints.", "Build/rebuild decision memo; option matrix; recommended path; cost/risk tradeoffs.", "Decision includes evidence, tradeoffs, cost ranges, and a clear production path.", "3-7 business days", "$5K-$18K", "Product advisor, architect", "Decision memo, option matrix, scope guardrails", "decision,rewrite,scope", 6),
                module("validation", "validation.scope_extraction", "scope-extraction", "Scope extraction", "Extract implementation scope from prototype behavior, docs, tickets, screenshots, or recorded walkthroughs.", "A vague product becomes a practical delivery scope without losing critical workflows.", "Prototype access, screenshots, docs, user journeys, owner walkthrough notes.", "Scope map; workflow inventory; acceptance criteria draft; out-of-scope list.", "Scope separates must-have production workflows from nice-to-have future work.", "3-7 business days", "$4K-$16K", "Product advisor, UX reviewer", "Scope map, workflow inventory, acceptance draft", "scope,intake,workflows", 7),
                module("validation", "validation.business_alignment", "business-alignment", "Business alignment review", "Connect technical services to customer value, revenue path, operating model, and launch priorities.", "Service investment stays tied to business outcome, not engineering activity alone.", "Business model, customer segment, pricing assumptions, launch target, operating constraints.", "Alignment memo; service priority rationale; success metrics; owner decision gates.", "Each service has a business reason, success metric, and owner approval point.", "3-5 business days", "$4K-$14K", "Product advisor, owner strategist", "Alignment memo, success metrics, decision gates", "business,outcome,prioritization", 8),

                module("code-rewrite-refactor", "code.refactor", "code-refactor", "Code refactor", "Improve structure, boundaries, readability, testability, and maintainability without changing product behavior.", "The codebase becomes easier to modify safely for production delivery.", "Repo access, critical flows, test commands, known brittle areas.", "Refactored modules; tests; code notes; risk register update.", "Core behavior is preserved and changed code is covered by agreed verification evidence.", "1-4 weeks", "$12K-$80K", "Senior engineer, QA reviewer", "Pull requests, test output, regression checklist", "refactor,maintainability", 11),
                module("code-rewrite-refactor", "code.backend_rewrite", "backend-rewrite-refactor", "Backend rewrite", "Rebuild or reshape backend services, APIs, jobs, integrations, and domain boundaries.", "Core backend workflows become reliable, observable, and maintainable enough for production.", "Repo access, API inventory, data model, logs, critical workflows, integration notes.", "Backend implementation; API notes; migration path; tests; release evidence.", "Backend paths are documented, tested, deployable, observable, and do not regress agreed workflows.", "2-6 weeks", "$24K-$120K", "Backend lead, database engineer, QA reviewer", "API contract, test report, deployment note, migration evidence", "backend,api,rewrite", 12),
                module("code-rewrite-refactor", "code.frontend_rewrite", "frontend-rewrite-refactor", "Frontend rewrite", "Modernize frontend architecture, routing, state, role views, responsive behavior, and design system usage.", "Owner and user workflows become polished, connected to APIs, accessible, and production-ready.", "Routes, design references, component library notes, API contracts, browser targets.", "Frontend implementation; responsive QA; accessibility notes; state/route documentation.", "Core screens render without blocking errors and match role-specific workflow expectations.", "2-5 weeks", "$18K-$90K", "Frontend lead, UX reviewer, QA reviewer", "Responsive screenshots, accessibility review, route test evidence", "frontend,ui,ux", 13),
                module("code-rewrite-refactor", "code.no_code_migration", "no-code-migration", "No-code migration", "Move a product from no-code tooling into a maintainable custom codebase or stable hybrid architecture.", "The business keeps useful validated workflows while gaining ownership, extensibility, and production control.", "No-code app access, data export, workflow map, integration list, ownership constraints.", "Migration plan; target architecture; data migration; replacement implementation; rollback notes.", "Critical workflows are migrated, validated, and handed off without unmanaged vendor lock-in.", "3-10 weeks", "$35K-$180K", "Full-stack lead, data engineer, product advisor", "Migration plan, data export evidence, workflow parity checks", "migration,no-code,custom-build", 14),
                module("code-rewrite-refactor", "code.ai_cleanup", "ai-built-app-cleanup", "AI-built app cleanup", "Turn AI-generated or rapidly assembled code into a secure, maintainable product foundation.", "The product stops depending on fragile generated code patterns and gains clear ownership.", "Repo access, generated code context, secrets policy, known runtime issues, target workflows.", "Cleanup plan; refactored code; security fixes; tests; documentation.", "Generated-code risks are identified, remediated, and documented with human review evidence.", "1-5 weeks", "$15K-$95K", "Senior engineer, security reviewer", "Code review, secret scan, test evidence, maintainability notes", "ai-built,cleanup,quality", 15),
                module("code-rewrite-refactor", "code.api_redesign", "api-redesign", "API redesign", "Redesign API boundaries, contracts, versioning, validation, errors, pagination, and integration behavior.", "External and internal integrations become predictable, secure, and easier to evolve.", "API inventory, consumers, error logs, auth model, payload examples.", "API contract; redesigned endpoints; compatibility notes; integration tests.", "API changes have documented contracts, migration notes, validation, and test coverage.", "1-4 weeks", "$12K-$70K", "Backend lead, integration engineer", "OpenAPI contract, integration tests, migration notes", "api,contract,integration", 16),
                module("code-rewrite-refactor", "code.auth_rebuild", "auth-rebuild", "Auth rebuild", "Rebuild authentication flows, session handling, account recovery, and provider integration.", "Users can sign in and access the right product areas safely and reliably.", "Auth provider setup, role matrix, protected routes, session policy, account flow requirements.", "Auth implementation; session policy; access tests; recovery flow notes.", "Auth flows are protected, tested, and role-aware across backend and frontend.", "1-4 weeks", "$12K-$75K", "Security engineer, backend lead, frontend lead", "Auth tests, role matrix, session notes", "auth,sessions,roles", 17),
                module("code-rewrite-refactor", "code.multitenant_refactor", "multitenant-refactor", "Multi-tenant refactor", "Introduce tenant boundaries, ownership rules, query isolation, and administrative controls.", "The product can serve multiple customers without cross-tenant data risk.", "Data model, tenant rules, user roles, API routes, reporting needs.", "Tenant model; access rules; migration plan; isolation tests.", "Tenant data access is enforced and verified at API, query, and UI boundaries.", "3-8 weeks", "$35K-$180K", "Backend lead, database engineer, security reviewer", "Tenant isolation tests, migration evidence, role matrix", "tenant,isolation,rbac", 18),
                module("code-rewrite-refactor", "code.legacy_modernization", "legacy-modernization", "Legacy modernization", "Modernize older frameworks, dependencies, build tooling, and deployment assumptions.", "A working legacy product becomes safer to maintain and easier to deploy.", "Repo access, dependency list, runtime versions, deployment process, known constraints.", "Upgrade plan; dependency updates; compatibility fixes; build/deploy evidence.", "Modernized stack builds, tests, deploys, and documents remaining compatibility risk.", "2-8 weeks", "$24K-$160K", "Senior engineer, DevOps reviewer", "Build logs, dependency report, deployment evidence", "legacy,upgrade,modernization", 19),

                module("security", "security.readiness_review", "security-readiness-review", "Security readiness review", "Review product security posture before launch, pilot, enterprise demo, or customer onboarding.", "Owners know which security risks block launch and which can be scheduled after launch.", "Architecture notes, auth setup, data types, API inventory, dependency list.", "Security readiness report; prioritized findings; remediation path.", "Findings are evidence-backed and no unsupported compliance certification is claimed.", "1-2 weeks", "$10K-$40K", "Security reviewer, technical lead", "Security report, risk register, remediation plan", "security,readiness,risk", 21),
                module("security", "security.secrets_scan", "secrets-scan", "Secrets scan", "Identify exposed credentials, environment leaks, token misuse, and secret handling issues.", "Credential risk is reduced before production access is granted.", "Repo access, environment variable list, deployment settings, secret storage details.", "Secret scan findings; rotation plan; secret storage guidance; verification notes.", "Exposed or risky secrets are documented, rotated where needed, and moved to approved storage.", "2-5 business days", "$4K-$18K", "Security engineer, DevOps reviewer", "Secret scan report, rotation evidence, storage notes", "secrets,credentials,scan", 22),
                module("security", "security.auth_review", "auth-access-control-review", "Authentication review", "Review authentication, sessions, account flows, and provider configuration.", "Authentication becomes trustworthy enough for real customers and teams.", "Auth provider config, session policy, account recovery flows, protected routes.", "Auth findings; remediation plan; test cases; launch checklist.", "Auth risks are mapped to concrete fixes and verified with role-aware tests.", "1-3 weeks", "$12K-$55K", "Security engineer, backend lead", "Auth findings, session review, test cases", "auth,session,security", 23),
                module("security", "security.rbac_review", "rbac-review", "RBAC review", "Review role-based access control, admin actions, ownership checks, and privilege boundaries.", "Users only perform actions appropriate to their role and resource ownership.", "Role matrix, API authorization code, protected UI routes, admin workflows.", "RBAC findings; policy matrix; access-control tests.", "Role checks protect sensitive actions in backend APIs and frontend navigation.", "1-3 weeks", "$10K-$45K", "Security engineer, backend lead", "Role matrix, authorization test evidence", "rbac,authorization,roles", 24),
                module("security", "security.api_review", "api-security-review", "API security review", "Review APIs, webhooks, rate limits, validation, tenant boundaries, and risky integrations.", "API surface is safer before external teams, customers, or automated tools depend on it.", "API inventory, OpenAPI docs, webhook providers, auth model, logs, recent incidents.", "API security findings; prioritized fixes; verification notes; hardening checklist.", "Critical API risks are documented with reproduction evidence or clear reasoning and mapped to fixes.", "1-4 weeks", "$14K-$70K", "Security engineer, backend lead", "API findings, rate limit checks, webhook validation evidence", "api,webhooks,security", 25),
                module("security", "security.dependency_review", "dependency-security-review", "Dependency security review", "Review vulnerable packages, supply-chain risk, upgrade pressure, and patch strategy.", "Dependency risk is visible and patchable before production launch or enterprise review.", "Dependency manifests, lockfiles, build pipeline, runtime versions.", "Dependency report; patch plan; upgrade PRs; residual risk notes.", "Critical vulnerabilities are patched or explicitly accepted with owner-visible rationale.", "3-10 business days", "$5K-$28K", "Security engineer, senior engineer", "Dependency scan, patch evidence, exception log", "dependencies,supply-chain,patching", 26),
                module("security", "security.payment_review", "payment-security-review", "Payment security review", "Review checkout, billing webhooks, entitlements, refunds, invoice access, and payment event handling.", "Payment workflows become safer and auditable before revenue operations scale.", "Payment provider setup, webhook code, billing roles, entitlement model, invoice workflows.", "Payment security findings; webhook verification; entitlement test notes.", "Payment events are verified, auditable, idempotent, and protected from unauthorized access.", "1-3 weeks", "$12K-$60K", "Security engineer, payments engineer", "Webhook tests, entitlement checks, payment risk report", "payments,webhooks,entitlements", 27),
                module("security", "security.data_privacy_review", "data-privacy-review", "Data privacy review", "Review sensitive data collection, storage, retention, export, deletion, and access visibility.", "Product data handling is explicit and safer for customer trust and operational review.", "Data inventory, user roles, storage locations, retention assumptions, export/delete needs.", "Privacy risk map; data handling notes; retention/export recommendations.", "Sensitive data handling is documented and mapped to technical controls.", "1-3 weeks", "$10K-$55K", "Privacy reviewer, backend lead", "Data inventory, retention notes, privacy risk register", "privacy,data,retention", 28),
                module("security", "security.fix_sprint", "security-fix-sprint", "Security fix sprint", "Implement prioritized security remediations from a readiness, API, auth, or dependency review.", "Known security blockers move from report to verified remediation.", "Security findings, repo access, acceptance criteria, deployment path.", "Security fixes; verification evidence; residual risk note.", "Fixes address agreed findings and include proof through tests, scans, or review notes.", "1-4 weeks", "$12K-$85K", "Security engineer, implementation lead", "Fix PRs, verification evidence, residual risk log", "security,remediation,fixes", 29),
                module("security", "security.evidence_review", "security-evidence-review", "Security evidence review", "Validate that security claims have real evidence before owner approval or enterprise review.", "Owners can trust security status without inflated compliance language.", "Findings, scan reports, test output, deployment notes, access-control evidence.", "Evidence review notes; missing proof list; approval recommendation.", "Security evidence is current, relevant, and linked to acceptance criteria.", "2-5 business days", "$4K-$20K", "Security reviewer, quality reviewer", "Evidence review, proof checklist, approval note", "security,evidence,review", 30),

                module("cloud-devops", "cloud.deployment_setup", "cloud-deployment", "Deployment setup", "Set up production and staging deployment with ownership, rollback, and release controls.", "The product can be deployed repeatedly and understood by future operators.", "Cloud account, domains, env vars, build command, runtime needs, rollback expectations.", "Production/staging environments; deployment notes; rollback process; ownership matrix.", "Deployment can be repeated, observed, rolled back, and handed off without hidden operator knowledge.", "1-4 weeks", "$12K-$80K", "DevOps engineer, backend/frontend leads", "Deployment logs, environment docs, rollback evidence", "deployment,staging,production", 31),
                module("cloud-devops", "cloud.staging_setup", "staging-setup", "Staging setup", "Create a production-like staging environment for QA, owner review, and release approval.", "Owners and teams can validate changes before customer-facing release.", "Cloud provider access, runtime config, test data needs, domain/subdomain plan.", "Staging environment; access notes; seed/test data approach; validation checklist.", "Staging mirrors production-critical configuration without exposing real customer data.", "1-2 weeks", "$6K-$28K", "DevOps engineer, QA reviewer", "Staging URL, access notes, validation checklist", "staging,qa,environment", 32),
                module("cloud-devops", "cloud.cicd_setup", "ci-cd-setup", "CI/CD setup", "Create build, test, security, and deployment pipelines with clear release feedback.", "Teams can ship with repeatable checks instead of manual release guesswork.", "Repo access, branch strategy, test/build commands, deployment target, secret policy.", "Pipeline configuration; required checks; release notes; failed-check triage guide.", "Pipeline runs on agreed branch events and blocks release on failing gates.", "1-3 weeks", "$8K-$40K", "DevOps engineer, QA reviewer", "CI logs, deployment logs, release checklist", "ci,cd,pipeline", 33),
                module("cloud-devops", "cloud.rollback_setup", "rollback-setup", "Rollback setup", "Define and test rollback procedures for app, database, configuration, and release incidents.", "Launch risk drops because failed releases have an operational recovery path.", "Deployment process, migration strategy, hosting provider, incident expectations.", "Rollback runbook; rollback drill evidence; release risk notes.", "Rollback path is documented and tested against agreed failure scenarios.", "1-2 weeks", "$6K-$30K", "DevOps engineer, database engineer", "Rollback runbook, drill evidence, release notes", "rollback,release,resilience", 34),
                module("cloud-devops", "cloud.monitoring_setup", "monitoring-setup", "Monitoring setup", "Configure uptime, error, logs, metrics, synthetic checks, and alert ownership.", "Teams see production issues before owners or customers discover them.", "Critical paths, expected traffic, incident channels, telemetry provider.", "Monitoring dashboard; alert rules; escalation notes; health report template.", "Alerts cover critical paths and include accountable response ownership.", "1-3 weeks", "$8K-$45K", "DevOps engineer, support lead", "Dashboard, alert rules, escalation matrix", "monitoring,alerts,observability", 35),
                module("cloud-devops", "cloud.logging_alerting", "logging-alerting", "Logging and alerting", "Improve structured logging, alert routing, error grouping, and event context.", "Incidents become diagnosable without searching raw logs or guessing ownership.", "Log sources, alert channels, error patterns, critical events, privacy constraints.", "Structured logs; alert routing; error grouping; runbook context.", "Logs support incident diagnosis without leaking sensitive data.", "1-3 weeks", "$8K-$35K", "DevOps engineer, backend lead", "Log examples, alert evidence, runbook links", "logging,alerts,incidents", 36),
                module("cloud-devops", "cloud.backup_restore", "backup-restore", "Backup and restore", "Set and validate backup/restore readiness for databases, files, and critical configuration.", "Recovery is documented before migrations, launch, or production incidents.", "Database provider, file storage, RPO/RTO target, retention requirements, restore environment.", "Backup policy; restore runbook; recovery drill evidence; retention plan.", "Restore process is documented and tested in a non-production environment.", "1-2 weeks", "$6K-$24K", "DevOps engineer, database engineer", "Restore drill, backup policy, retention notes", "backup,restore,recovery", 37),
                module("cloud-devops", "cloud.cost_review", "cloud-cost-review", "Cloud cost review", "Review hosting, storage, data transfer, observability, and environment costs.", "Cloud spend is understandable and scaled to product stage.", "Cloud bills, resource inventory, traffic estimates, environment plan.", "Cost report; savings recommendations; scaling cost model.", "Cost recommendations preserve reliability and clearly show tradeoffs.", "3-7 business days", "$4K-$18K", "Cloud engineer, finance-aware reviewer", "Cost report, resource inventory, savings plan", "cost,cloud,finops", 38),
                module("cloud-devops", "cloud.env_config_audit", "environment-config-audit", "Environment configuration audit", "Review environment variables, secrets, runtime flags, domain config, and provider settings.", "Environment drift and missing configuration stop blocking release confidence.", "Env var list, deployment target, secret policy, provider settings, runtime logs.", "Configuration audit; missing env list; drift notes; remediation checklist.", "Required configuration is documented, owned, and safe for staging/production.", "2-5 business days", "$4K-$16K", "DevOps engineer, backend lead", "Env audit, config checklist, secret storage notes", "env,config,secrets", 39),
                module("cloud-devops", "cloud.deployment_handoff", "deployment-handoff", "Deployment handoff", "Package deployment knowledge into owner/team runbooks and operational transfer.", "The owner is not dependent on one person remembering how production works.", "Deployment notes, provider access, release process, incident expectations.", "Deployment handoff doc; access matrix; release checklist; rollback notes.", "A new accountable operator can deploy, verify, and roll back using the handoff material.", "3-7 business days", "$4K-$18K", "DevOps engineer, delivery lead", "Handoff doc, access matrix, release checklist", "handoff,deployment,runbook", 40),

                module("database", "db.review", "database-review", "Database review", "Review schema, migrations, indexes, integrity, backups, reporting, and operational risk.", "Data risk becomes visible before it slows launch, migration, or growth.", "Schema dump, query logs, migration history, backup policy, reporting needs.", "Database health report; risk map; remediation plan.", "Findings map database risk to clear fixes, owners, and evidence.", "1-2 weeks", "$8K-$30K", "Database engineer, backend lead", "DB report, query plans, migration review", "database,review,data", 41),
                module("database", "db.schema_redesign", "database-redesign", "Schema redesign", "Improve schema structure, constraints, relationships, migrations, and data ownership.", "The product data model supports production workflows and future reporting.", "Current schema, product workflows, migration constraints, data quality issues.", "Schema changes; migration scripts; data integrity notes; query evidence.", "Migration path is documented, validated, and protects existing data.", "2-6 weeks", "$20K-$110K", "Database engineer, backend lead", "Migration scripts, ERD, data validation evidence", "schema,migration,postgres", 42),
                module("database", "db.migration_plan", "database-migration-plan", "Migration plan", "Plan data migration from old schemas, no-code tools, spreadsheets, or external systems.", "Migration risk is understood before production data moves.", "Source data, target schema, volume, quality issues, downtime tolerance.", "Migration plan; mapping document; test strategy; rollback plan.", "Plan identifies data mapping, validation, rollback, and owner acceptance criteria.", "1-3 weeks", "$10K-$45K", "Database engineer, product advisor", "Mapping doc, test plan, rollback plan", "migration,data,planning", 43),
                module("database", "db.migration_execution", "database-migration-execution", "Migration execution", "Execute validated migrations with checks, rollback, and owner-visible evidence.", "Data moves safely into the production-ready system.", "Approved migration plan, source/target access, validation criteria, downtime window.", "Migration scripts; execution evidence; validation report; rollback status.", "Migration meets agreed validation checks and has clear residual risk notes.", "1-6 weeks", "$18K-$140K", "Database engineer, DevOps engineer", "Execution logs, validation report, rollback notes", "migration,execution,data", 44),
                module("database", "db.query_optimization", "query-optimization", "Query optimization", "Improve slow queries, indexes, N+1 patterns, pagination, and reporting performance.", "Critical workflows stay fast as product usage and data volume grow.", "Slow query logs, traces, database access, traffic assumptions, top workflows.", "Optimized queries; index changes; benchmark evidence; monitoring notes.", "Performance improves against agreed benchmarks without unsafe data-model changes.", "1-4 weeks", "$8K-$60K", "Database engineer, backend lead", "Query plans, benchmark results, index migration", "queries,indexes,performance", 45),
                module("database", "db.backup_validation", "backup-validation", "Backup validation", "Verify backup coverage, retention, restore timing, and disaster recovery assumptions.", "Backup claims become evidence-backed rather than provider settings screenshots.", "Backup config, restore target, RPO/RTO expectations, storage policy.", "Backup validation report; restore drill; retention recommendations.", "Restore is tested and documented with measured recovery timing.", "3-7 business days", "$4K-$20K", "Database engineer, DevOps engineer", "Restore evidence, retention policy, recovery timing", "backup,restore,database", 46),
                module("database", "db.data_integrity", "data-integrity-review", "Data integrity review", "Review constraints, duplicates, orphaned records, auditability, and reporting correctness.", "Owners can trust core product data and operational reports.", "Schema, sample data, reporting queries, workflows, known data quality issues.", "Data quality findings; constraint plan; cleanup recommendations.", "Critical integrity risks have reproducible examples and remediation plans.", "1-3 weeks", "$8K-$45K", "Database engineer, data analyst", "Data quality report, cleanup plan, validation checks", "integrity,quality,data", 47),
                module("database", "db.analytics_readiness", "analytics-readiness", "Analytics readiness", "Prepare product data for event tracking, metrics, reporting, and operational dashboards.", "Business metrics become trackable and trusted after launch.", "Analytics goals, event taxonomy, data sources, reporting needs, privacy constraints.", "Analytics schema; event map; reporting model; validation checklist.", "Metrics are tied to product events and can be validated against source behavior.", "1-4 weeks", "$10K-$60K", "Data engineer, product analyst", "Event taxonomy, dashboard spec, validation report", "analytics,events,reporting", 48),
                module("database", "db.tenant_isolation", "tenant-isolation-review", "Tenant isolation review", "Review tenant keys, queries, admin access, background jobs, and report boundaries.", "Multi-customer data stays isolated under real production use.", "Tenant model, role matrix, data model, API routes, admin workflows.", "Tenant isolation findings; tests; remediation plan.", "Tenant boundaries are verified across API, database, jobs, and UI workflows.", "1-4 weeks", "$12K-$75K", "Database engineer, security reviewer", "Isolation tests, tenant model, access review", "tenant,isolation,data", 49),

                module("scaling", "scale.performance_audit", "performance-audit", "Performance audit", "Find bottlenecks across frontend rendering, backend APIs, database queries, queues, and hosting.", "The owner knows exactly where performance investment should go first.", "Traffic assumptions, traces, logs, database metrics, hosting plan, top journeys.", "Performance report; prioritized bottlenecks; benchmark evidence; remediation plan.", "Findings include reproduction steps, impact, tradeoffs, and remediation sequence.", "1-3 weeks", "$10K-$45K", "Performance engineer, backend/frontend leads", "Benchmark report, trace evidence, remediation plan", "performance,audit,scale", 51),
                module("scaling", "scale.load_testing", "load-testing", "Load testing", "Design and run load tests for critical user journeys, APIs, background jobs, and data paths.", "The team understands capacity before launch or growth campaigns.", "Critical paths, traffic goals, staging environment, data setup, success criteria.", "Load scripts; test report; bottleneck list; remediation recommendations.", "Load tests are repeatable and results are tied to production-readiness decisions.", "1-3 weeks", "$8K-$50K", "Performance engineer, DevOps engineer", "Load scripts, test report, capacity notes", "load,test,capacity", 52),
                module("scaling", "scale.frontend_optimization", "frontend-optimization", "Frontend optimization", "Improve bundle size, rendering, hydration, caching, assets, and browser performance.", "User-facing workflows feel fast and stable on target devices.", "Core pages, performance traces, browser targets, design constraints, analytics.", "Optimized frontend; metrics report; responsive performance evidence.", "Core pages meet agreed performance targets without visual or functional regression.", "1-4 weeks", "$10K-$65K", "Frontend performance engineer", "Lighthouse traces, bundle report, screenshot QA", "frontend,performance,ux", 53),
                module("scaling", "scale.backend_optimization", "backend-optimization", "Backend optimization", "Improve API latency, concurrency, jobs, caching, connection use, and service boundaries.", "Backend throughput and reliability improve without guesswork.", "API traces, logs, code paths, traffic assumptions, database metrics.", "Backend optimizations; benchmark evidence; monitoring notes.", "Latency and reliability improve against agreed service-level targets.", "1-5 weeks", "$12K-$85K", "Backend lead, performance engineer", "API benchmarks, traces, deployment notes", "backend,performance,latency", 54),
                module("scaling", "scale.database_optimization", "database-optimization", "Database optimization", "Optimize queries, indexes, locks, connection pools, and high-volume data access.", "Data-backed workflows stay stable under real load.", "Slow query logs, schema, traffic assumptions, top APIs, monitoring access.", "DB optimizations; query plans; benchmark evidence; regression checks.", "Database performance improves while preserving data correctness and migration safety.", "1-5 weeks", "$12K-$90K", "Database engineer, backend lead", "Query plans, index migrations, benchmark report", "database,performance,indexes", 55),
                module("scaling", "scale.caching_setup", "caching-setup", "Caching setup", "Add safe caching for API responses, expensive computations, sessions, or assets.", "The product gains speed without stale-data surprises.", "Data volatility, cache candidates, invalidation needs, traffic profile.", "Caching implementation; invalidation notes; performance evidence.", "Cache behavior is documented, tested, and safe for critical data changes.", "1-3 weeks", "$8K-$45K", "Backend lead, DevOps engineer", "Cache policy, test evidence, performance report", "cache,redis,performance", 56),
                module("scaling", "scale.queue_setup", "queue-setup", "Queue setup", "Move slow or fragile work into background queues with retries, idempotency, and monitoring.", "Long-running operations become reliable and observable.", "Job candidates, failure modes, retry requirements, hosting/runtime constraints.", "Queue implementation; retry policy; worker monitoring; failure runbook.", "Queued work is idempotent, observable, and has clear failure handling.", "1-4 weeks", "$12K-$70K", "Backend lead, DevOps engineer", "Queue config, retry evidence, worker dashboard", "queue,background-jobs,retries", 57),
                module("scaling", "scale.architecture_review", "scale-architecture-review", "Scale architecture review", "Review architecture for growth bottlenecks, resilience gaps, and cost/complexity tradeoffs.", "Owners can choose a scale path that fits product stage and budget.", "Architecture diagram, traffic goals, bottlenecks, cost constraints, team capacity.", "Scale architecture report; phased path; cost/risk model.", "Recommendations are sequenced and avoid premature complexity.", "1-2 weeks", "$10K-$45K", "Architect, performance engineer", "Architecture review, scale roadmap, cost model", "architecture,scale,resilience", 58),
                module("scaling", "scale.cost_to_scale", "cost-to-scale-review", "Cost-to-scale review", "Estimate infrastructure, data, observability, and team operating cost at growth levels.", "The business understands what scaling will cost before usage spikes.", "Current bill, architecture, traffic forecast, data/storage forecast, SLA expectations.", "Cost-to-scale model; optimization options; trigger points.", "Cost model ties spend to usage and identifies when architecture changes are justified.", "3-7 business days", "$5K-$20K", "Cloud engineer, architect", "Cost model, usage assumptions, trigger plan", "cost,scale,forecast", 59),

                module("launch-gtm-readiness", "launch.readiness_review", "launch-readiness", "Launch readiness", "Validate product, engineering, support, analytics, payment, and operational readiness before go-live.", "Launch decisions are evidence-backed and owner-approved.", "Release target, staging access, support flow, analytics, payment, onboarding notes.", "Launch checklist; go/no-go decision; blocker map; owner approval record.", "Launch-critical workflows have evidence, owners, and approval status.", "1-3 weeks", "$10K-$50K", "Launch lead, QA reviewer, support reviewer", "Launch checklist, approval record, blocker map", "launch,readiness,go-live", 61),
                module("launch-gtm-readiness", "launch.onboarding_review", "onboarding-review", "Onboarding review", "Review first-run, activation, account setup, help states, and owner/customer handoff.", "New users can understand and activate the product with less support friction.", "Onboarding flow, user types, analytics, support docs, activation goals.", "Onboarding findings; flow improvements; activation metrics; acceptance criteria.", "Onboarding flow is understandable, measurable, and aligned with target users.", "1-3 weeks", "$8K-$35K", "Product advisor, UX reviewer", "Onboarding review, activation metric plan, screenshots", "onboarding,activation,ux", 62),
                module("launch-gtm-readiness", "launch.admin_console", "admin-console-readiness", "Admin console readiness", "Prepare admin workflows, audit visibility, support controls, and operational roles.", "Owners and support teams can operate the product after launch.", "Admin tasks, roles, support actions, audit needs, customer management workflows.", "Admin readiness plan; workflow fixes; audit/control checklist.", "Critical admin tasks are role-protected, documented, and tested.", "1-4 weeks", "$12K-$70K", "Full-stack lead, support reviewer", "Admin checklist, role tests, workflow evidence", "admin,operations,roles", 63),
                module("launch-gtm-readiness", "launch.analytics_setup", "analytics-payments-onboarding-readiness", "Analytics setup", "Define and implement event tracking, operational metrics, funnel visibility, and owner dashboards.", "Owners can measure activation, delivery health, revenue flow, and product usage.", "Business goals, event taxonomy, analytics provider, user journeys, privacy constraints.", "Analytics events; dashboards; validation notes; metric definitions.", "Metrics are validated and tied to product/business decisions.", "1-4 weeks", "$10K-$60K", "Product analyst, frontend/backend leads", "Event validation, dashboard screenshots, metric dictionary", "analytics,events,dashboard", 64),
                module("launch-gtm-readiness", "launch.payment_setup", "payment-setup", "Payment setup", "Implement or harden checkout, billing, invoices, entitlements, and payment webhooks.", "Revenue workflows become testable, reliable, and auditable.", "Payment provider, pricing model, entitlement rules, invoice needs, tax/accounting constraints.", "Payment flow; webhook handling; entitlement tests; billing runbook.", "Payments are idempotent, audited, role-protected, and tested with provider events.", "1-5 weeks", "$14K-$90K", "Payments engineer, security reviewer", "Webhook evidence, entitlement tests, billing checklist", "payments,billing,revenue", 65),
                module("launch-gtm-readiness", "launch.notifications_setup", "notifications-setup", "Notifications setup", "Implement email, push, webhook, or in-app notification flows with delivery visibility.", "Critical product and operational messages reach the right users.", "Notification types, recipients, channels, templates, provider credentials, consent rules.", "Notification implementation; templates; delivery logs; retry policy.", "Notifications are routed, retryable, observable, and safe for user preferences.", "1-4 weeks", "$10K-$60K", "Backend lead, frontend lead", "Templates, delivery logs, retry tests", "notifications,email,push", 66),
                module("launch-gtm-readiness", "launch.support_readiness", "support-readiness", "Support readiness", "Prepare support inbox, triage, escalation, known-issue tracking, and response ownership.", "Customers can get help without the product team improvising support operations.", "Support channels, SLA targets, known issues, team roles, escalation path.", "Support runbook; triage workflow; SLA plan; known issue list.", "Support workflows have owners, expected responses, and escalation rules.", "1-2 weeks", "$6K-$28K", "Support lead, delivery manager", "Support runbook, SLA notes, escalation matrix", "support,sla,triage", 67),
                module("launch-gtm-readiness", "launch.documentation_setup", "documentation-setup", "Documentation setup", "Create product, technical, support, release, and handoff documentation needed for launch.", "Users, owners, and operators know how the product works and what changed.", "Existing docs, product flows, release notes, support questions, technical architecture.", "Documentation set; handoff notes; release guide; support articles.", "Docs are current, owner-readable, and linked to launch-critical workflows.", "1-3 weeks", "$6K-$35K", "Technical writer, delivery lead", "Docs, release guide, handoff notes", "docs,handoff,launch", 68),
                module("launch-gtm-readiness", "launch.beta_management", "beta-management", "Beta management", "Set up beta cohorts, feedback intake, issue triage, release gates, and communication cadence.", "Beta learning becomes structured input for production readiness.", "Beta goals, participant list, feedback channel, release cadence, known risks.", "Beta plan; feedback workflow; issue triage; release decision notes.", "Beta feedback is tracked, prioritized, and tied to launch decisions.", "1-4 weeks", "$8K-$45K", "Product advisor, delivery manager", "Beta plan, feedback board, decision log", "beta,feedback,release", 69),
                module("launch-gtm-readiness", "launch.go_live_checklist", "go-live-checklist", "Go-live checklist", "Create and validate final release, monitoring, support, rollback, analytics, and owner approval checklist.", "Go-live is a controlled decision instead of a hopeful deployment.", "Launch plan, deployment path, monitoring, support, payment, analytics, owner approvals.", "Go-live checklist; sign-off record; rollback plan; launch command notes.", "Checklist is complete, evidence-linked, and approved by accountable owners.", "3-7 business days", "$4K-$18K", "Launch lead, DevOps engineer", "Checklist, sign-off record, command notes", "go-live,checklist,approval", 70),

                module("operations-support", "support.basic_maintenance", "support-package", "Basic maintenance", "Provide ongoing product maintenance for bug fixes, dependency updates, small improvements, and release support.", "The product remains operable after initial delivery.", "Known issues, repo access, support expectations, release process, ownership map.", "Maintenance scope; support cadence; issue workflow; release notes.", "Maintenance boundaries and response expectations are agreed and visible.", "Ongoing", "$6K-$25K/mo", "Support lead, implementation engineer", "Issue log, release notes, maintenance report", "maintenance,support,operations", 71),
                module("operations-support", "support.monitoring", "support-monitoring", "Support monitoring", "Monitor product health, alerts, incidents, and service-level signals after launch.", "The owner sees product health and risk without waiting for customer complaints.", "Monitoring dashboard, alert channels, SLA targets, incident roles.", "Monitoring coverage; weekly/monthly health summary; escalation notes.", "Monitoring reports show status, incidents, actions, and remaining risk.", "Ongoing", "$3K-$18K/mo", "Support lead, DevOps engineer", "Health report, alert history, escalation notes", "monitoring,support,health", 72),
                module("operations-support", "support.incident_response", "incident-response", "Incident response", "Run incident triage, communication, mitigation, root-cause, and follow-up tracking.", "Production incidents are handled with visible ownership and learning.", "Incident channel, severity policy, system access, runbooks, stakeholder list.", "Incident timeline; mitigation notes; root-cause summary; follow-up actions.", "Incident records include timeline, impact, decisions, and corrective actions.", "On demand", "$4K-$30K/incident", "Incident lead, DevOps engineer, support lead", "Incident report, RCA, follow-up plan", "incident,rca,response", 73),
                module("operations-support", "support.bug_triage", "bug-triage", "Bug triage", "Prioritize, reproduce, route, and verify product bugs with owner-visible decisions.", "Bugs stop becoming an unmanaged backlog of vague complaints.", "Bug reports, logs, user impact, product priorities, release plan.", "Triage board; reproduction notes; priority decisions; verification evidence.", "Bugs are reproducible, prioritized, assigned, and verified after fix.", "Ongoing", "$3K-$18K/mo", "QA reviewer, support lead", "Triage notes, reproduction steps, verification evidence", "bugs,triage,qa", 74),
                module("operations-support", "support.release_management", "release-management", "Release management", "Manage release scope, checks, notes, deployment windows, approvals, and rollback readiness.", "Releases become predictable and auditable.", "Release cadence, branch strategy, checks, owner approvals, stakeholder needs.", "Release plan; release notes; approval record; rollback readiness.", "Releases include scope, evidence, approvals, and post-release verification.", "Ongoing", "$4K-$22K/mo", "Delivery manager, DevOps engineer", "Release notes, approval record, deployment evidence", "release,change-management", 75),
                module("operations-support", "support.monthly_health_review", "monthly-health-review", "Monthly health review", "Review product health, incidents, performance, costs, security posture, and support trends.", "Owners get a recurring decision view of product operations.", "Monitoring data, support requests, incident history, cost data, release notes.", "Health report; trend analysis; recommendations; action plan.", "Health report is evidence-backed and separates urgent fixes from planned improvements.", "Monthly", "$3K-$15K/mo", "Support lead, product advisor", "Health report, action plan, trend dashboard", "health,reporting,ops", 76),
                module("operations-support", "support.security_patching", "security-patching", "Security patching", "Track and apply dependency, runtime, and security updates with release verification.", "The product stays safer after launch without chaotic emergency upgrades.", "Dependency scan, runtime versions, release process, rollback policy.", "Patch plan; update PRs; verification evidence; exception notes.", "Patches are applied, tested, and documented with residual risk exceptions.", "Ongoing", "$4K-$20K/mo", "Security engineer, support engineer", "Patch log, scan report, test evidence", "patching,security,dependencies", 77),
                module("operations-support", "support.cloud_cost_monitoring", "cloud-cost-monitoring", "Cloud cost monitoring", "Track cloud spend, resource drift, utilization, and cost anomalies after launch.", "Cloud spend stays visible and aligned with product stage.", "Cloud billing access, resource inventory, traffic expectations, budget targets.", "Cost dashboard; anomaly notes; monthly recommendations.", "Cost changes are explained and linked to usage, incidents, or resource drift.", "Ongoing", "$2K-$12K/mo", "Cloud engineer, support lead", "Cost report, anomaly log, optimization notes", "cost,cloud,monitoring", 78),
                module("operations-support", "support.handoff", "support-handoff", "Support handoff", "Transfer operational knowledge, known issues, credentials policy, runbooks, and support process.", "A new team can support the product without tribal knowledge.", "Runbooks, architecture notes, support channels, known issues, deployment process.", "Handoff package; access matrix; support runbook; known issue register.", "Handoff material is complete enough for a new operator to triage, deploy, and escalate.", "1-2 weeks", "$6K-$28K", "Delivery manager, support lead", "Handoff docs, access matrix, runbooks", "handoff,support,operations", 79),
                module("operations-support", "support.growth_retainer", "growth-retainer", "Growth retainer", "Provide ongoing improvements, operational support, scaling work, and launch iteration capacity.", "Owners have a stable path for post-launch growth without re-scoping every small change.", "Roadmap, support needs, usage metrics, known risks, release cadence.", "Retainer scope; monthly plan; delivery reports; backlog health.", "Retainer work has clear boundaries, monthly outcomes, and owner-visible reporting.", "Ongoing", "$10K-$60K/mo", "Delivery manager, full-stack team, support lead", "Monthly plan, delivery report, backlog health", "retainer,growth,operations", 80)
        );

        Map<String, ServiceModule> modules = new LinkedHashMap<>();
        for (ModuleSeed seed : seeds) {
            ServiceModule module = moduleRepository.findByStableCode(seed.stableCode())
                    .or(() -> moduleRepository.findBySlug(seed.slug()))
                    .orElseGet(ServiceModule::new);
            module.setCategory(categories.get(seed.categorySlug()));
            module.setStableCode(seed.stableCode());
            module.setSlug(seed.slug());
            module.setServiceLayer(seed.categorySlug());
            module.setName(seed.name());
            module.setDescription(seed.description());
            module.setOwnerOutcome(seed.ownerOutcome());
            module.setRequiredInputs(seed.requiredInputs());
            module.setExpectedDeliverables(seed.expectedDeliverables());
            module.setAcceptanceCriteria(seed.acceptanceCriteria());
            module.setTimelineRange(seed.timelineRange());
            module.setPriceRange(seed.priceRange());
            module.setWorkflowSteps("Diagnose scope; confirm access and evidence; implement or review; validate acceptance criteria; hand off decisions and operating notes.");
            module.setRequiredEvidenceTypes(seed.requiredEvidenceTypes());
            module.setSuggestedTeamRoles(seed.suggestedTeamRoles());
            module.setAiAssistanceTags(seed.aiAssistanceTags());
            module.setHumanReviewRequired(true);
            module.setVisible(true);
            module.setReleaseStage("production-ready");
            module.setMaturityLevel("managed-service");
            module.setSourceAliases(seed.stableCode() + "," + seed.slug());
            module.setSortOrder(seed.sortOrder());
            module.setActive(true);
            modules.put(seed.stableCode(), moduleRepository.save(module));
        }
        return modules;
    }

    private void seedDependencies(Map<String, ServiceModule> modules) {
        List<DependencySeed> seeds = List.of(
                dependency("code.backend_rewrite", "db.schema_redesign", "Backend rewrites often change schema, migrations, and data ownership.", ServiceDependency.DependencyType.HARD, ServiceDependency.DependencySeverity.BLOCKER),
                dependency("code.frontend_rewrite", "validation.requirements", "Frontend rewrite should be grounded in accepted user workflows and role-specific requirements.", ServiceDependency.DependencyType.HARD, ServiceDependency.DependencySeverity.WARNING),
                dependency("code.no_code_migration", "db.migration_plan", "No-code migration needs a data and workflow migration plan before execution.", ServiceDependency.DependencyType.HARD, ServiceDependency.DependencySeverity.BLOCKER),
                dependency("code.auth_rebuild", "security.rbac_review", "Auth rebuild needs role and ownership rules to avoid insecure access paths.", ServiceDependency.DependencyType.HARD, ServiceDependency.DependencySeverity.BLOCKER),
                dependency("code.multitenant_refactor", "db.tenant_isolation", "Multi-tenant code changes must include database tenant-isolation verification.", ServiceDependency.DependencyType.HARD, ServiceDependency.DependencySeverity.BLOCKER),
                dependency("security.payment_review", "launch.payment_setup", "Payment security findings should flow into payment implementation and verification.", ServiceDependency.DependencyType.PARALLEL, ServiceDependency.DependencySeverity.WARNING),
                dependency("cloud.deployment_setup", "cloud.cicd_setup", "Production deployment needs repeatable CI/CD checks.", ServiceDependency.DependencyType.HARD, ServiceDependency.DependencySeverity.BLOCKER),
                dependency("cloud.deployment_setup", "cloud.monitoring_setup", "Production deployment needs monitoring before support handoff.", ServiceDependency.DependencyType.HARD, ServiceDependency.DependencySeverity.BLOCKER),
                dependency("cloud.deployment_setup", "cloud.backup_restore", "Live systems need backup and restore readiness.", ServiceDependency.DependencyType.HARD, ServiceDependency.DependencySeverity.WARNING),
                dependency("cloud.rollback_setup", "cloud.cicd_setup", "Rollback work depends on a known release pipeline and deployment path.", ServiceDependency.DependencyType.HARD, ServiceDependency.DependencySeverity.WARNING),
                dependency("db.migration_execution", "db.migration_plan", "Migration execution requires an approved migration plan.", ServiceDependency.DependencyType.HARD, ServiceDependency.DependencySeverity.BLOCKER),
                dependency("scale.load_testing", "cloud.staging_setup", "Load testing needs a staging or test environment that can absorb synthetic traffic.", ServiceDependency.DependencyType.ACCESS, ServiceDependency.DependencySeverity.WARNING),
                dependency("scale.database_optimization", "db.query_optimization", "Database optimization should use query-level evidence and index plans.", ServiceDependency.DependencyType.SOFT, ServiceDependency.DependencySeverity.RECOMMENDED),
                dependency("launch.go_live_checklist", "cloud.rollback_setup", "Go-live needs a rollback plan before owner approval.", ServiceDependency.DependencyType.HARD, ServiceDependency.DependencySeverity.BLOCKER),
                dependency("launch.go_live_checklist", "launch.support_readiness", "Go-live needs support ownership and escalation paths.", ServiceDependency.DependencyType.HARD, ServiceDependency.DependencySeverity.WARNING),
                dependency("support.handoff", "cloud.deployment_handoff", "Support handoff needs deployment handoff details for safe operations.", ServiceDependency.DependencyType.HARD, ServiceDependency.DependencySeverity.WARNING),
                dependency("support.security_patching", "security.dependency_review", "Patching should be driven by dependency review evidence.", ServiceDependency.DependencyType.SOFT, ServiceDependency.DependencySeverity.RECOMMENDED)
        );
        for (DependencySeed seed : seeds) {
            ServiceModule source = modules.get(seed.sourceCode());
            ServiceModule target = modules.get(seed.targetCode());
            if (source == null || target == null) {
                continue;
            }
            ServiceDependency dependency = dependencyRepository.findBySourceModuleId(source.getId()).stream()
                    .filter(existing -> existing.getDependsOnModule().getId().equals(target.getId()))
                    .findFirst()
                    .orElseGet(ServiceDependency::new);
            dependency.setSourceModule(source);
            dependency.setDependsOnModule(target);
            dependency.setReason(seed.reason());
            dependency.setMessage(seed.reason());
            dependency.setDependencyType(seed.type());
            dependency.setSeverity(seed.severity());
            dependency.setRequired(seed.severity() == ServiceDependency.DependencySeverity.BLOCKER);
            dependency.setRuleMetadata("{\"source\":\"catalog-core-seed\"}");
            dependencyRepository.save(dependency);
        }
    }

    private void seedPackageTemplates(Map<String, ServiceModule> modules) {
        List<PackageTemplateSeed> seeds = List.of(
                template("prototype-stabilization", "Prototype Stabilization", "Stabilize a prototype into a delivery-ready product foundation.", "PROTOTYPE", "$25K-$95K", "4-8 weeks", "validated prototype with fragile code or missing production controls", List.of("validation.product_readiness", "validation.requirements", "code.refactor", "security.readiness_review", "cloud.staging_setup")),
                template("saas-launch-readiness", "SaaS Launch Readiness", "Prepare SaaS product for beta, paid launch, or customer rollout.", "VALIDATED", "$45K-$180K", "6-12 weeks", "SaaS owner moving toward customers and revenue", List.of("validation.launch_risk", "cloud.cicd_setup", "cloud.deployment_setup", "cloud.monitoring_setup", "cloud.rollback_setup", "security.api_review", "launch.analytics_setup", "launch.payment_setup", "launch.support_readiness", "launch.go_live_checklist")),
                template("no-code-migration", "No-Code Migration", "Move useful no-code workflows into a maintainable product platform.", "PROTOTYPE", "$50K-$220K", "8-16 weeks", "owner outgrowing no-code tooling", List.of("validation.scope_extraction", "code.no_code_migration", "db.migration_plan", "db.migration_execution", "cloud.deployment_setup", "support.handoff")),
                template("ai-built-app-cleanup", "AI-Built App Cleanup", "Turn AI-generated app code into a human-owned product base.", "PROTOTYPE", "$30K-$130K", "4-10 weeks", "product assembled quickly with generated code", List.of("validation.codebase", "code.ai_cleanup", "security.secrets_scan", "security.auth_review", "cloud.cicd_setup", "launch.documentation_setup")),
                template("security-hardening", "Security Hardening", "Reduce launch risk across auth, APIs, dependencies, and evidence.", "VALIDATED", "$30K-$150K", "4-10 weeks", "product needing security proof before launch or enterprise review", List.of("security.readiness_review", "security.secrets_scan", "security.auth_review", "security.api_review", "security.dependency_review", "security.fix_sprint", "security.evidence_review")),
                template("cloud-foundation", "Cloud Foundation", "Set environments, deployment, monitoring, backup, and operational handoff.", "PROTOTYPE", "$35K-$160K", "4-10 weeks", "product with unclear hosting or manual deploys", List.of("cloud.staging_setup", "cloud.deployment_setup", "cloud.cicd_setup", "cloud.monitoring_setup", "cloud.backup_restore", "cloud.deployment_handoff")),
                template("database-rescue", "Database Rescue", "Repair schema, migrations, query health, backups, and integrity.", "LIVE", "$30K-$170K", "4-12 weeks", "product blocked by data quality or performance risk", List.of("db.review", "db.schema_redesign", "db.query_optimization", "db.data_integrity", "db.backup_validation")),
                template("scale-readiness", "Scale Readiness", "Prepare a working product for higher traffic and operating cost control.", "SCALING", "$40K-$190K", "5-12 weeks", "live product expecting growth", List.of("scale.performance_audit", "scale.load_testing", "scale.backend_optimization", "scale.database_optimization", "scale.caching_setup", "scale.cost_to_scale")),
                template("mobile-optimization", "Mobile Optimization", "Improve mobile app performance, stability, onboarding, notifications, and launch readiness.", "VALIDATED", "$35K-$175K", "5-12 weeks", "mobile app with quality, activation, performance, or release-readiness risk", List.of("scale.performance_audit", "scale.frontend_optimization", "launch.onboarding_review", "launch.notifications_setup", "cloud.monitoring_setup", "launch.beta_management")),
                template("fintech-productization", "Fintech Productization", "Govern payments, risk, security, data, and operational handoff.", "VALIDATED", "$80K-$300K", "8-18 weeks", "payments, billing, ledger, or regulated workflow product", List.of("validation.business_alignment", "security.payment_review", "launch.payment_setup", "db.data_integrity", "security.api_review", "cloud.monitoring_setup", "launch.go_live_checklist")),
                template("enterprise-pilot-readiness", "Enterprise Pilot Readiness", "Prepare proof, controls, support, and docs for an enterprise pilot.", "VALIDATED", "$55K-$220K", "6-14 weeks", "owner preparing for enterprise buyer scrutiny", List.of("validation.launch_risk", "security.evidence_review", "launch.documentation_setup", "launch.admin_console", "support.handoff", "support.monthly_health_review")),
                template("ongoing-operations", "Ongoing Operations", "Operate, monitor, patch, release, and improve a launched product.", "LIVE", "$12K-$75K/mo", "ongoing", "live product needing dependable operations", List.of("support.basic_maintenance", "support.monitoring", "support.incident_response", "support.release_management", "support.security_patching", "support.monthly_health_review"))
        );
        for (PackageTemplateSeed seed : seeds) {
            PackageTemplate template = packageTemplateRepository.findBySlug(seed.slug()).orElseGet(PackageTemplate::new);
            template.setSlug(seed.slug());
            template.setName(seed.name());
            template.setDescription(seed.description());
            template.setTargetProductStage(seed.stage());
            template.setBudgetRange(seed.budget());
            template.setTimelineRange(seed.timeline());
            template.setCustomerFit(seed.fit());
            template.setOutcomeSummary("A governed service plan with dependencies, milestones, acceptance criteria, evidence, team matching, and handoff readiness.");
            template.setAiReadinessNotes("Template exposes clean inputs and expected outputs for a future AI integration layer, but composition remains deterministic and human-reviewed.");
            template.setHumanReviewRequired(true);
            template.setActive(true);
            template.setSortOrder(seeds.indexOf(seed) + 1);
            template = packageTemplateRepository.save(template);
            int order = 1;
            for (String serviceCode : seed.serviceCodes()) {
                ServiceModule module = modules.get(serviceCode);
                if (module == null) {
                    continue;
                }
                PackageTemplateModule templateModule = packageTemplateModuleRepository
                        .findByTemplateIdAndServiceModuleId(template.getId(), module.getId())
                        .orElseGet(PackageTemplateModule::new);
                templateModule.setTemplate(template);
                templateModule.setServiceModule(module);
                templateModule.setSequenceOrder(order);
                templateModule.setRequired(order <= Math.max(3, seed.serviceCodes().size() - 1));
                templateModule.setPhaseName(order <= 2 ? "Discover and validate" : order <= 5 ? "Build and harden" : "Launch and operate");
                templateModule.setRationale("Included because " + module.getName() + " is part of the " + seed.name() + " production path.");
                packageTemplateModuleRepository.save(templateModule);
                order++;
            }
        }
    }

    private void seedTemplateDefinitions() {
        List<TemplateDefinitionSeed> seeds = List.of(
                templateDefinition("product-intake-v1", CatalogTemplateDefinition.TemplateType.INTAKE, "Product intake", "Structured owner brief for productization planning.", "Product name, stage, users, business goal, constraints, risks.", "Collect product context, production goal, current blockers, technical access, data sensitivity, and launch timing.", "{\"product\":\"object\",\"goal\":\"string\",\"risks\":\"array\",\"constraints\":\"array\"}", 1),
                templateDefinition("diagnosis-report-v1", CatalogTemplateDefinition.TemplateType.DIAGNOSIS, "Diagnosis report", "Evidence-backed readiness diagnosis.", "Product intake, repo/deployment evidence, owner notes.", "Summarize health, blockers, service recommendations, dependencies, and owner decisions.", "{\"healthScore\":\"number\",\"findings\":\"array\",\"recommendedServices\":\"array\"}", 2),
                templateDefinition("service-plan-v1", CatalogTemplateDefinition.TemplateType.PACKAGE, "Service plan", "Dependency-aware package composition.", "Selected services, product goal, constraints, dependency evaluation.", "Generate service sequence, milestones, acceptance criteria, evidence needs, and team roles.", "{\"modules\":\"array\",\"milestones\":\"array\",\"evidence\":\"array\",\"roles\":\"array\"}", 3),
                templateDefinition("milestone-acceptance-v1", CatalogTemplateDefinition.TemplateType.ACCEPTANCE_CRITERION, "Milestone acceptance", "Owner-readable acceptance criteria.", "Service module, deliverables, evidence types, milestone state.", "Define passed, failed, and change-request conditions with human approval requirement.", "{\"criteria\":\"array\",\"decision\":\"enum\",\"evidenceLinks\":\"array\"}", 4),
                templateDefinition("evidence-packet-v1", CatalogTemplateDefinition.TemplateType.EVIDENCE, "Evidence packet", "Artifact checklist for milestone review.", "Milestone, deliverables, test outputs, deployment links, documents.", "Collect implementation artifacts, test evidence, screenshots, logs, and owner notes.", "{\"artifacts\":\"array\",\"reviewStatus\":\"enum\"}", 5),
                templateDefinition("handoff-runbook-v1", CatalogTemplateDefinition.TemplateType.HANDOFF, "Handoff runbook", "Operational handoff for owners and support teams.", "Deployment notes, access matrix, monitoring, rollback, known issues.", "Document how to deploy, observe, triage, escalate, and maintain the product.", "{\"runbook\":\"object\",\"accessMatrix\":\"array\",\"knownIssues\":\"array\"}", 6),
                templateDefinition("support-health-v1", CatalogTemplateDefinition.TemplateType.SUPPORT, "Support health review", "Recurring operating review.", "Support requests, incidents, releases, monitoring, costs, security patches.", "Summarize health, trend, risk, decisions, and next operational actions.", "{\"summary\":\"string\",\"risks\":\"array\",\"actions\":\"array\"}", 7),
                templateDefinition("ai-context-contract-v1", CatalogTemplateDefinition.TemplateType.AI_CONTEXT, "AI context contract", "Future AI layer input contract.", "Catalog IDs, evidence IDs, user role, product/workspace IDs.", "Restrict AI support to cited platform data and human-reviewed recommendations.", "{\"allowedSources\":\"array\",\"forbiddenClaims\":\"array\",\"requiresHumanReview\":true}", 8)
        );
        for (TemplateDefinitionSeed seed : seeds) {
            CatalogTemplateDefinition definition = templateDefinitionRepository.findBySlug(seed.slug()).orElseGet(CatalogTemplateDefinition::new);
            definition.setSlug(seed.slug());
            definition.setTemplateType(seed.type());
            definition.setName(seed.name());
            definition.setDescription(seed.description());
            definition.setRequiredInputs(seed.requiredInputs());
            definition.setContent(seed.content());
            definition.setOutputContract(seed.outputContract());
            definition.setSortOrder(seed.sortOrder());
            definition.setActive(true);
            templateDefinitionRepository.save(definition);
        }
    }

    private void seedRules(Map<String, ServiceModule> modules) {
        List<RuleSeed> seeds = List.of(
                rule("goal-payments-security", CatalogRule.RuleType.GOAL_KEYWORD, "payment", null, "security.payment_review", ServiceDependency.DependencySeverity.WARNING, "Payment products should include payment security and entitlement review."),
                rule("goal-enterprise-evidence", CatalogRule.RuleType.GOAL_KEYWORD, "enterprise", null, "security.evidence_review", ServiceDependency.DependencySeverity.RECOMMENDED, "Enterprise paths usually need evidence review before buyer-facing claims."),
                rule("goal-launch-support", CatalogRule.RuleType.GOAL_KEYWORD, "launch", null, "launch.go_live_checklist", ServiceDependency.DependencySeverity.WARNING, "Launch goals should include a go-live checklist."),
                rule("goal-scale-load", CatalogRule.RuleType.GOAL_KEYWORD, "scale", null, "scale.load_testing", ServiceDependency.DependencySeverity.RECOMMENDED, "Scaling goals should include repeatable load tests."),
                rule("selected-auth-rbac", CatalogRule.RuleType.SERVICE_SELECTED, "code.auth_rebuild", "code.auth_rebuild", "security.rbac_review", ServiceDependency.DependencySeverity.BLOCKER, "Auth rebuild must include role and ownership verification."),
                rule("selected-deploy-handoff", CatalogRule.RuleType.SERVICE_SELECTED, "cloud.deployment_setup", "cloud.deployment_setup", "cloud.deployment_handoff", ServiceDependency.DependencySeverity.RECOMMENDED, "Deployment setup should finish with handoff documentation."),
                rule("selected-support-health", CatalogRule.RuleType.SERVICE_SELECTED, "support.basic_maintenance", "support.basic_maintenance", "support.monthly_health_review", ServiceDependency.DependencySeverity.RECOMMENDED, "Ongoing maintenance should include a recurring owner health review.")
        );
        int order = 1;
        for (RuleSeed seed : seeds) {
            ServiceModule recommended = modules.get(seed.recommendedCode());
            if (recommended == null) {
                continue;
            }
            CatalogRule rule = ruleRepository.findBySlug(seed.slug()).orElseGet(CatalogRule::new);
            rule.setSlug(seed.slug());
            rule.setRuleType(seed.type());
            rule.setTriggerKey(seed.triggerKey());
            rule.setSourceModule(seed.sourceCode() == null ? null : modules.get(seed.sourceCode()));
            rule.setRecommendedModule(recommended);
            rule.setSeverity(seed.severity());
            rule.setMessage(seed.message());
            rule.setRuleMetadata("{\"source\":\"catalog-core-seed\",\"aiReady\":true,\"aiExecuted\":false}");
            rule.setHumanReviewRequired(true);
            rule.setActive(true);
            rule.setSortOrder(order++);
            ruleRepository.save(rule);
        }
    }

    private void seedAiCapabilityConfigs() {
        List<AIConfigSeed> seeds = List.of(
                ai("product-diagnosis-assist", "Product Diagnosis Assist", "DIAGNOSIS", "Suggest diagnosis findings from owner-provided evidence and platform records."),
                ai("service-plan-assist", "Service Plan Assist", "PACKAGE_COMPOSITION", "Suggest service sequences using catalog IDs, dependencies, templates, and evidence state."),
                ai("team-match-explain", "Team Match Explanation", "TEAM_MATCHING", "Explain why a verified team or solo expert fits a service plan."),
                ai("milestone-review-assist", "Milestone Review Assist", "MILESTONE_REVIEW", "Summarize evidence and risks for human milestone approval."),
                ai("support-triage-assist", "Support Triage Assist", "SUPPORT_TRIAGE", "Suggest support priority, owner, and next response from workspace evidence."),
                ai("admin-governance-audit", "Admin Governance Audit", "ADMIN_GOVERNANCE", "Find catalog drift, missing evidence requirements, and unsupported claims.")
        );
        int order = 1;
        for (AIConfigSeed seed : seeds) {
            AICapabilityConfig config = aiCapabilityConfigRepository.findBySlug(seed.slug()).orElseGet(AICapabilityConfig::new);
            config.setSlug(seed.slug());
            config.setName(seed.name());
            config.setCapabilityType(seed.type());
            config.setDescription(seed.description());
            config.setInputContract("{\"allowedInputs\":[\"catalogIds\",\"productId\",\"workspaceId\",\"evidenceIds\",\"userRole\"],\"requiresTenantScope\":true}");
            config.setOutputContract("{\"recommendations\":\"array\",\"rationale\":\"string\",\"citations\":\"array\",\"confidence\":\"number\",\"requiresHumanReview\":true}");
            config.setAllowedSources("ProdUS catalog, product records, package modules, workspace milestones, evidence attachments, support records.");
            config.setForbiddenClaims("No legal, compliance, security certification, production guarantee, or uncited claim may be produced.");
            config.setHumanReviewRequired(true);
            config.setEnabled(false);
            config.setSortOrder(order++);
            aiCapabilityConfigRepository.save(config);
        }
    }

    private ModuleSeed module(
            String categorySlug,
            String stableCode,
            String slug,
            String name,
            String description,
            String ownerOutcome,
            String requiredInputs,
            String expectedDeliverables,
            String acceptanceCriteria,
            String timelineRange,
            String priceRange,
            String suggestedTeamRoles,
            String requiredEvidenceTypes,
            String aiAssistanceTags,
            int sortOrder
    ) {
        return new ModuleSeed(categorySlug, stableCode, slug, name, description, ownerOutcome, requiredInputs, expectedDeliverables, acceptanceCriteria, timelineRange, priceRange, suggestedTeamRoles, requiredEvidenceTypes, aiAssistanceTags, sortOrder);
    }

    private DependencySeed dependency(String sourceCode, String targetCode, String reason, ServiceDependency.DependencyType type, ServiceDependency.DependencySeverity severity) {
        return new DependencySeed(sourceCode, targetCode, reason, type, severity);
    }

    private PackageTemplateSeed template(String slug, String name, String description, String stage, String budget, String timeline, String fit, List<String> serviceCodes) {
        return new PackageTemplateSeed(slug, name, description, stage, budget, timeline, fit, serviceCodes);
    }

    private TemplateDefinitionSeed templateDefinition(String slug, CatalogTemplateDefinition.TemplateType type, String name, String description, String requiredInputs, String content, String outputContract, int sortOrder) {
        return new TemplateDefinitionSeed(slug, type, name, description, requiredInputs, content, outputContract, sortOrder);
    }

    private RuleSeed rule(String slug, CatalogRule.RuleType type, String triggerKey, String sourceCode, String recommendedCode, ServiceDependency.DependencySeverity severity, String message) {
        return new RuleSeed(slug, type, triggerKey, sourceCode, recommendedCode, severity, message);
    }

    private AIConfigSeed ai(String slug, String name, String type, String description) {
        return new AIConfigSeed(slug, name, type, description);
    }

    public record CatalogSeedResult(int categories, int modules) {}
    private record CategorySeed(String slug, String name, String description, int sortOrder) {}
    private record ModuleSeed(String categorySlug, String stableCode, String slug, String name, String description, String ownerOutcome, String requiredInputs, String expectedDeliverables, String acceptanceCriteria, String timelineRange, String priceRange, String suggestedTeamRoles, String requiredEvidenceTypes, String aiAssistanceTags, int sortOrder) {}
    private record DependencySeed(String sourceCode, String targetCode, String reason, ServiceDependency.DependencyType type, ServiceDependency.DependencySeverity severity) {}
    private record PackageTemplateSeed(String slug, String name, String description, String stage, String budget, String timeline, String fit, List<String> serviceCodes) {}
    private record TemplateDefinitionSeed(String slug, CatalogTemplateDefinition.TemplateType type, String name, String description, String requiredInputs, String content, String outputContract, int sortOrder) {}
    private record RuleSeed(String slug, CatalogRule.RuleType type, String triggerKey, String sourceCode, String recommendedCode, ServiceDependency.DependencySeverity severity, String message) {}
    private record AIConfigSeed(String slug, String name, String type, String description) {}
}
