package com.easyluxury.ai.controller;

import com.easyluxury.ai.dto.AIGenerationRequest;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureWebMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.TestPropertySource;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;
import org.springframework.web.context.WebApplicationContext;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

/**
 * AI Auto-Generated Controller Integration Test
 * 
 * Comprehensive integration tests for auto-generated AI API endpoints
 * including content generation, embedding generation, and semantic search.
 * 
 * @author Easy Luxury Team
 * @version 1.0.0
 */
@SpringBootTest(classes = {com.easyluxury.EasyLuxuryApplication.class, com.ai.infrastructure.config.AIInfrastructureAutoConfiguration.class})
@AutoConfigureWebMvc
@ActiveProfiles("test")
@TestPropertySource(properties = {
    "ai.providers.openai.api-key=test-key",
    "ai.providers.openai.model=gpt-4o-mini",
    "ai.service.enabled=true"
})
class AIAutoGeneratedControllerIntegrationTest {

    @Autowired
    private WebApplicationContext webApplicationContext;

    @Autowired
    private ObjectMapper objectMapper;

    private MockMvc mockMvc;

    private void setupMockMvc() {
        mockMvc = MockMvcBuilders.webAppContextSetup(webApplicationContext).build();
    }

    @Test
    void testContentGenerationEndpoint() throws Exception {
        setupMockMvc();
        
        AIGenerationRequest request = AIGenerationRequest.builder()
            .prompt("Generate a product description for a luxury watch")
            .model("gpt-4o-mini")
            .maxTokens(200)
            .temperature(0.7)
            .build();

        mockMvc.perform(post("/api/v1/ai/auto-generated/content-generation")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.content").exists())
                .andExpect(jsonPath("$.model").value("gpt-4o-mini"))
                .andExpect(jsonPath("$.requestId").exists())
                .andExpect(jsonPath("$.processingTimeMs").exists());
    }

    @Test
    void testEmbeddingGenerationEndpoint() throws Exception {
        setupMockMvc();
        
        String requestJson = """
            {
                "text": "Luxury watch with diamond bezel",
                "model": "text-embedding-3-small"
            }
            """;

        mockMvc.perform(post("/api/v1/ai/auto-generated/embedding-generation")
                .contentType(MediaType.APPLICATION_JSON)
                .content(requestJson))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.embedding").exists())
                .andExpect(jsonPath("$.model").value("text-embedding-3-small"))
                .andExpect(jsonPath("$.requestId").exists())
                .andExpect(jsonPath("$.processingTimeMs").exists());
    }

    @Test
    void testSemanticSearchEndpoint() throws Exception {
        setupMockMvc();
        
        String requestJson = """
            {
                "query": "luxury watch",
                "entityType": "products",
                "limit": 10
            }
            """;

        mockMvc.perform(post("/api/v1/ai/auto-generated/semantic-search")
                .contentType(MediaType.APPLICATION_JSON)
                .content(requestJson))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.results").exists())
                .andExpect(jsonPath("$.totalResults").exists())
                .andExpect(jsonPath("$.query").value("luxury watch"))
                .andExpect(jsonPath("$.requestId").exists())
                .andExpect(jsonPath("$.processingTimeMs").exists());
    }

    @Test
    void testRecommendationEndpoint() throws Exception {
        setupMockMvc();
        
        String requestJson = """
            {
                "userId": "user123",
                "context": "luxury products",
                "limit": 5
            }
            """;

        mockMvc.perform(post("/api/v1/ai/auto-generated/recommendation")
                .contentType(MediaType.APPLICATION_JSON)
                .content(requestJson))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.recommendations").exists())
                .andExpect(jsonPath("$.userId").value("user123"))
                .andExpect(jsonPath("$.context").value("luxury products"))
                .andExpect(jsonPath("$.requestId").exists())
                .andExpect(jsonPath("$.processingTimeMs").exists());
    }

    @Test
    void testValidationEndpoint() throws Exception {
        setupMockMvc();
        
        String requestJson = """
            {
                "content": "This is a test content for validation",
                "rules": {
                    "minLength": 10,
                    "maxLength": 1000
                }
            }
            """;

        mockMvc.perform(post("/api/v1/ai/auto-generated/validation")
                .contentType(MediaType.APPLICATION_JSON)
                .content(requestJson))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.isValid").exists())
                .andExpect(jsonPath("$.score").exists())
                .andExpect(jsonPath("$.issues").exists())
                .andExpect(jsonPath("$.suggestions").exists())
                .andExpect(jsonPath("$.content").value("This is a test content for validation"))
                .andExpect(jsonPath("$.requestId").exists())
                .andExpect(jsonPath("$.processingTimeMs").exists());
    }

    @Test
    void testAPISpecificationEndpoint() throws Exception {
        setupMockMvc();
        
        mockMvc.perform(get("/api/v1/ai/auto-generated/specification"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.title").value("AI Infrastructure API"))
                .andExpect(jsonPath("$.version").value("1.0.0"))
                .andExpect(jsonPath("$.description").exists())
                .andExpect(jsonPath("$.baseUrl").value("/api/v1/ai"))
                .andExpect(jsonPath("$.endpoints").exists())
                .andExpect(jsonPath("$.openApiSpec").exists());
    }

    @Test
    void testClientSDKGenerationEndpoint() throws Exception {
        setupMockMvc();
        
        mockMvc.perform(get("/api/v1/ai/auto-generated/sdk/java"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.language").value("java"))
                .andExpect(jsonPath("$.code").exists())
                .andExpect(jsonPath("$.generatedAt").exists());
    }

    @Test
    void testClientSDKGenerationForTypeScript() throws Exception {
        setupMockMvc();
        
        mockMvc.perform(get("/api/v1/ai/auto-generated/sdk/typescript"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.language").value("typescript"))
                .andExpect(jsonPath("$.code").exists())
                .andExpect(jsonPath("$.generatedAt").exists());
    }

    @Test
    void testClientSDKGenerationForPython() throws Exception {
        setupMockMvc();
        
        mockMvc.perform(get("/api/v1/ai/auto-generated/sdk/python"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.language").value("python"))
                .andExpect(jsonPath("$.code").exists())
                .andExpect(jsonPath("$.generatedAt").exists());
    }

    @Test
    void testClientSDKGenerationForCurl() throws Exception {
        setupMockMvc();
        
        mockMvc.perform(get("/api/v1/ai/auto-generated/sdk/curl"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.language").value("curl"))
                .andExpect(jsonPath("$.code").exists())
                .andExpect(jsonPath("$.generatedAt").exists());
    }

    @Test
    void testInvalidLanguageSDKGeneration() throws Exception {
        setupMockMvc();
        
        mockMvc.perform(get("/api/v1/ai/auto-generated/sdk/invalid"))
                .andExpect(status().isInternalServerError());
    }
}